In [1]:
import os
import sys
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from scipy import stats
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Malgun Gothic'
import matplotlib.dates as mdates

def get_hstr(path):
    hstr = pd.read_csv(path)
    hstr['datetime'] = pd.to_datetime(hstr['CLCT_UNIX_TM'], unit='s', utc=True)
    hstr['datetime'] = hstr['datetime'].dt.tz_convert('Asia/Seoul').dt.strftime('%Y-%m-%d %H:%M:%S')
    hstr['datetime'] = hstr['datetime'].astype('datetime64[ns]')
    hstr.columns = ['현장교차로ID', '수집유닉스시각', '수집일시', '제어구분코드', '제어상태코드', '주기시간', '옵셋시간',
        'A링1현시시간', 'A링2현시시간', 'A링3현시시간', 'A링4현시시간', 'A링5현시시간', 'A링6현시시간',
        'A링7현시시간', 'A링8현시시간', 'B링1현시시간', 'B링2현시시간', 'B링3현시시간', 'B링4현시시간',
        'B링5현시시간', 'B링6현시시간', 'B링7현시시간', 'B링8현시시간', 'A링1현시보행시간',
        'A링2현시보행시간', 'A링3현시보행시간', 'A링4현시보행시간', 'A링5현시보행시간', 'A링6현시보행시간',
        'A링7현시보행시간', 'A링8현시보행시간', 'B링1현시보행시간', 'B링2현시보행시간', 'B링3현시보행시간',
        'B링4현시보행시간', 'B링5현시보행시간', 'B링6현시보행시간', 'B링7현시보행시간', 'B링8현시보행시간',
        '수집날짜시각']
    cols = list(hstr.columns).copy()
    cols.remove('수집날짜시각')
    cols.insert(1, '수집날짜시각')
    hstr = hstr[cols]
    return hstr

inter_nos = list(range(5031, 5048))

In [2]:
# 성남시 신호이력 데이터
s_tod_his = pd.read_csv('seongnam/S_TOD_HIS_1702597659892.csv')

# 인천시 신호이력 데이터
'''SELECT * FROM soitdspotintsoperhstr WHERE SPOT_INTS_ID BETWEEN 5031 AND 5047'''
csv_files = [f for f in os.listdir('incheon') if f.endswith('.csv')]

dfs = []
for file in csv_files:
    df_name = file.replace('.csv', '')
    print(df_name)
    globals()[df_name] = get_hstr(f'incheon/{file}')
    dfs.append(globals()[df_name])
    print(sorted([dt for dt in globals()[df_name]['수집날짜시각'] if dt.hour != 23])[0])
    print(sorted([dt for dt in globals()[df_name]['수집날짜시각'] if dt.hour != 23])[-1])
hstr = pd.concat(dfs).drop_duplicates().sort_values(by='수집날짜시각').reset_index(drop=True)
hstr = hstr[['현장교차로ID', '수집날짜시각', '제어구분코드', '제어상태코드', '주기시간', '옵셋시간',
             'A링1현시시간', 'A링2현시시간', 'A링3현시시간', 'A링4현시시간', 'A링5현시시간', 'A링6현시시간',
             'B링1현시시간', 'B링2현시시간', 'B링3현시시간', 'B링4현시시간', 'B링5현시시간', 'B링6현시시간']]
hstr = hstr[hstr.수집날짜시각.dt.day >= 12]
print(len(hstr))
print(sorted([dt for dt in hstr['수집날짜시각'] if dt.hour != 23])[0])
print(sorted([dt for dt in hstr['수집날짜시각'] if dt.hour != 23])[-1])

soitdspotintsoperhstr_202312110921
2023-12-10 09:00:00
2023-12-11 09:21:31
soitdspotintsoperhstr_202312120814
2023-12-11 09:00:57
2023-12-12 08:14:02
soitdspotintsoperhstr_202312131102
2023-12-12 09:00:58
2023-12-13 11:02:54
soitdspotintsoperhstr_202312141254
2023-12-13 09:00:58
2023-12-14 12:53:54
soitdspotintsoperhstr_202312150926
2023-12-14 09:00:58
2023-12-15 09:26:01
soitdspotintsoperhstr_202312151700
2023-12-15 09:00:58
2023-12-15 16:59:54
32466
2023-12-12 00:00:09
2023-12-15 16:59:54

In [3]:
infos = {}
# 신호이력
infos['hstr'] = {inter_no:hstr_temp for (inter_no, hstr_temp) in hstr.groupby('현장교차로ID')}
# 현시 개수
infos['number_of_phases'] = {}
for inter_no in inter_nos:
    a_ring_columns = [col for col in infos['hstr'][inter_no].columns if 'A링' in col]
    b_ring_columns = [col for col in infos['hstr'][inter_no].columns if 'B링' in col]
    max_a_ring = max([int(col[2]) for col in a_ring_columns if infos['hstr'][inter_no][col].any() != 0])
    max_b_ring = max([int(col[2]) for col in b_ring_columns if infos['hstr'][inter_no][col].any() != 0])
    if max_a_ring == max_b_ring:
        infos['number_of_phases'][inter_no] = max_a_ring
    else:
        raise "A링, B링 현시번호 최댓값이 서로 다름"
# 현시시간 목록
infos['durations'] = {inter_no:np.unique(infos['hstr'][inter_no].iloc[:,4:].values.flatten()) for inter_no in inter_nos}

In [4]:
# TOD 계획 데이터
todplans = pd.read_csv("soitdtodplan_202312181440.csv")
todplans.columns = ["현장교차로ID", "시각계획번호", "시각운영번호", "수집유닉스시각", "수집일시", "시작시", "시작분", "현시운영번호", "현시운영계획번호"]
todplans = todplans[(todplans['수집일시'] == 20231212) & (todplans['시각계획번호'] == 1) & (todplans['시작시']!=0)]

# 전이시각, ID
infos['transition_times'] = {inter_no:todplans[todplans.현장교차로ID == inter_no][['시작시', '시작분']] for inter_no in inter_nos}
infos['ID'] = {inter_no:todplans[todplans.현장교차로ID == inter_no].현시운영계획번호.unique() for inter_no in inter_nos}

# 시간계획 데이터
timeplans = pd.read_csv("soitdtimeplan_202312180943.csv")
timeplans.columns = ["현장교차로ID", "시간계획번호", "현시운영번호", "현시운영계획번호", "수집유닉스시각", "수집일시", "주기시간", "옵셋시간",
                     "A링1현시시간", "A링2현시시간", "A링3현시시간", "A링4현시시간", "A링5현시시간", "A링6현시시간", "A링7현시시간", "A링8현시시간",
                     "B링1현시시간", "B링2현시시간", "B링3현시시간", "B링4현시시간", "B링5현시시간", "B링6현시시간", "B링7현시시간", "B링8현시시간"]
timeplans = timeplans[(timeplans.시간계획번호 == 1)]
timeplan_list = []
for inter_no in inter_nos:
    timeplan_list.append(timeplans[(timeplans.현장교차로ID==inter_no) & (timeplans.현시운영계획번호.isin(infos['ID'][inter_no]))])
timeplans = pd.concat(timeplan_list)

# 이상치로 판단하지 않는 현시시간 / 이상치로 판단하는 현시시간
infos['accepted_durations'] = {}
infos['unaccepted_durations'] = {}

# 현시시간 빈도, 옵셋
infos['unique_durations'] = {}
infos['duration_frequencies'] = {}
infos['offsets'] = {}
infos['cycles'] = {}

for inter_no in inter_nos:
    phase_times = np.unique(timeplans[timeplans.현장교차로ID == inter_no].iloc[:, 8:].values.flatten())
    accepted_phase_times = np.unique(np.concatenate([phase_times - 1, phase_times, phase_times + 1]))
    infos['accepted_durations'][inter_no] = accepted_phase_times
    unaccepted_phase_times = sorted(set(infos['durations'][inter_no]) - set(accepted_phase_times))
    infos['unaccepted_durations'][inter_no] = unaccepted_phase_times

    unique_durations, frequencies = np.unique(infos['hstr'][inter_no].iloc[:,6:].values, return_counts=True)
    sorted_indices = np.argsort(frequencies)[::-1]
    infos['unique_durations'][inter_no] = unique_durations[sorted_indices]
    infos['duration_frequencies'][inter_no] = frequencies[sorted_indices]

    infos['offsets'][inter_no] = {}
    infos['cycles'][inter_no] = {}
    for _, row in infos['transition_times'][inter_no].iterrows():
        hour = row.시작시
        minute = row.시작분
        ID = todplans[(todplans.현장교차로ID==inter_no) & (todplans.시작시==hour) & (todplans.시작분==minute)].iloc[0].현시운영계획번호
        offset = timeplans[(timeplans.현장교차로ID==inter_no)&(timeplans.현시운영계획번호==ID)].iloc[0].옵셋시간
        cycle = timeplans[(timeplans.현장교차로ID==inter_no)&(timeplans.현시운영계획번호==ID)].iloc[0].주기시간
        infos['offsets'][inter_no][(hour, minute)] = offset
        infos['cycles'][inter_no][(hour, minute)] = cycle

In [5]:
k = 3 # context number

# 이상치 dataframe, 이상치를 포함한 주변에 대한 dataframe, 정상 dataframe
infos['outlier_dfs'] = {}
infos['context_dfs'] = {}
infos['context_dfs_list'] = {}
infos['normal_dfs'] = {}
hstr_context = []
hstr_outlier = []
for inter_no in inter_nos:
    df = infos['hstr'][inter_no].sort_values(by='수집날짜시각').reset_index(drop=True)
    outliers = infos['unaccepted_durations'][inter_no]
    ring_columns = [col for col in df.columns if '현시시간' in col]
    outlier_indices = df[df[ring_columns].isin(outliers).any(axis=1)].index
    context_indices = [] # 각 아웃라이어 인덱스에 대해 위아래 네 행의 인덱스를 구합니다.
    context_indices_list = []
    for idx in outlier_indices:
        start_idx = max(idx - k, 0)  # 데이터프레임의 시작을 넘어가지 않도록 합니다.
        end_idx = min(idx + k + 1, len(df))  # 데이터프레임의 끝을 넘어가지 않도록 합니다.
        context_indices.extend(range(start_idx, end_idx))
        context_indices_list.append(list(range(start_idx, end_idx)))
    context_indices = sorted(context_indices)
    normal_indices = sorted(set(df.index) - set(outlier_indices))

    df['전이시간여부'] = False
    for _, row in infos['transition_times'][inter_no].iterrows():
        hour = row.시작시
        minute = row.시작분
        transition_range = ((df['수집날짜시각'].dt.hour==hour) & (df['수집날짜시각'].dt.minute >= minute) & (df['수집날짜시각'].dt.minute <= minute+20))
        df.loc[transition_range, '전이시간여부'] = True

    df['이상치존재'] = False
    df.loc[outlier_indices, '이상치존재'] = True

    infos['outlier_dfs'][inter_no] = df.iloc[outlier_indices].drop_duplicates()
    infos['context_dfs'][inter_no] = df.iloc[context_indices].drop_duplicates()
    infos['context_dfs_list'][inter_no] = []
    for context_indices_ in context_indices_list:
        infos['context_dfs_list'][inter_no].append(df.iloc[context_indices_])
    infos['normal_dfs'][inter_no]  = df.iloc[normal_indices]
    hstr_context.append(infos['context_dfs'][inter_no])
    hstr_outlier.append(infos['outlier_dfs'][inter_no])
hstr_context = pd.concat(hstr_context)
hstr_outlier = pd.concat(hstr_outlier)

In [21]:
dfs = []
for inter_no in inter_nos:
    DF = infos['context_dfs'][inter_no]
    temp = []
    for i in DF.index:
        if not temp or i == temp[-1] + 1:
            temp.append(i)
        else:
            dfs.append(DF.loc[temp])
            temp = [i]
    if temp:
        dfs.append(DF.loc[temp])

In [22]:
with pd.option_context('display.max_columns', None):
    display(pd.read_csv('incheon/soitdspotintsoperhstr_202312120814.csv'))

,SPOT_INTS_ID,CLCT_UNIX_TM,CLCT_DT,CTRL_SE_CD,CTRL_STTS_CD,CYCL_HR,OFST_HR,A_RING_1_PHAS_HR,A_RING_2_PHAS_HR,A_RING_3_PHAS_HR,A_RING_4_PHAS_HR,A_RING_5_PHAS_HR,A_RING_6_PHAS_HR,A_RING_7_PHAS_HR,A_RING_8_PHAS_HR,B_RING_1_PHAS_HR,B_RING_2_PHAS_HR,B_RING_3_PHAS_HR,B_RING_4_PHAS_HR,B_RING_5_PHAS_HR,B_RING_6_PHAS_HR,B_RING_7_PHAS_HR,B_RING_8_PHAS_HR,A_RING_1_PHAS_AMBL_HR,A_RING_2_PHAS_AMBL_HR,A_RING_3_PHAS_AMBL_HR,A_RING_4_PHAS_AMBL_HR,A_RING_5_PHAS_AMBL_HR,A_RING_6_PHAS_AMBL_HR,A_RING_7_PHAS_AMBL_HR,A_RING_8_PHAS_AMBL_HR,B_RING_1_PHAS_AMBL_HR,B_RING_2_PHAS_AMBL_HR,B_RING_3_PHAS_AMBL_HR,B_RING_4_PHAS_AMBL_HR,B_RING_5_PHAS_AMBL_HR,B_RING_6_PHAS_AMBL_HR,B_RING_7_PHAS_AMBL_HR,B_RING_8_PHAS_AMBL_HR
0,5046,1702393195,20231212,3,1,100,95,20,80,0,0,0,0,0,0,20,80,0,0,0,0,0,0,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,5036,1702336442,20231212,3,1,181,123,39,49,28,30,35,0,0,0,39,49,28,30,35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,5040,1702336439,20231212,3,1,180,119,41,83,16,40,0,0,0,0,41,83,16,40,0,0,0,0,0,38,0,32,0,0,0,0,32,36,0,0,0,0,0,0
3,5044,1702336439,20231212,3,1,180,120,40,62,20,20,22,16,0,0,40,62,20,20,22,16,0,0,36,34,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5032,1702336435,20231212,3,1,170,55,24,61,24,37,24,0,0,0,24,61,24,37,24,0,0,0,0,0,0,35,0,0,0,0,0,0,0,35,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9104,5039,1702252906,20231211,3,1,181,106,45,136,0,0,0,0,0,0,45,136,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9105,5033,1702252902,20231211,3,1,170,32,42,86,42,0,0,0,0,0,42,86,42,0,0,0,0,0,36,46,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9106,5043,1702252898,20231211,3,1,180,98,42,79,8,11,40,0,0,0,42,79,8,11,40,0,0,0,0,32,0,5,35,0,0,0,34,0,0,0,0,0,0,0
9107,5038,1702252888,20231211,3,1,169,19,26,74,49,20,0,0,0,0,26,74,49,20,0,0,0,0,0,0,0,17,0,0,0,0,21,32,21,0,0,0,0,0
9108,5037,1702252857,20231211,3,1,170,158,40,72,30,28,0,0,0,0,40,72,30,28,0,0,0,0,32,0,0,0,0,0,0,0,0,28,0,24,0,0,0,0

In [27]:
hstr.제어구분코드.value_counts()

제어구분코드
3    26873
0     5593
Name: count, dtype: int64

In [26]:
hstr.제어상태코드.value_counts()

제어상태코드
1    26118
0     5519
2      754
3       75
Name: count, dtype: int64

In [24]:
len(dfs)

591

In [7]:
import random
for _ in range(10):
    p = random.choice(range(len(dfs)))
    display(dfs[p])

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
671,5039,2023-12-13 06:58:04,3,1,170,94,45,125,0,0,0,0,45,125,0,0,0,0,False,False
672,5039,2023-12-13 07:00:56,3,1,171,96,45,126,0,0,0,0,45,126,0,0,0,0,True,False
673,5039,2023-12-13 07:03:45,3,1,169,45,45,124,0,0,0,0,45,124,0,0,0,0,True,False
674,5039,2023-12-13 07:07:44,3,2,239,104,45,194,0,0,0,0,45,194,0,0,0,0,True,True
675,5039,2023-12-13 07:10:45,3,1,181,105,45,136,0,0,0,0,45,136,0,0,0,0,True,False
676,5039,2023-12-13 07:13:45,3,1,180,106,45,135,0,0,0,0,45,135,0,0,0,0,True,False
677,5039,2023-12-13 07:16:44,3,1,179,104,45,134,0,0,0,0,45,134,0,0,0,0,True,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
900,5047,2023-12-13 22:28:32,3,1,170,162,33,69,24,44,0,0,33,69,24,44,0,0,False,False
901,5047,2023-12-13 22:31:22,3,1,170,162,33,69,24,44,0,0,33,69,24,44,0,0,True,False
902,5047,2023-12-13 22:34:12,3,1,170,132,33,69,24,44,0,0,33,69,24,44,0,0,True,False
903,5047,2023-12-13 22:37:14,3,2,182,154,35,74,23,50,0,0,35,74,23,50,0,0,True,True
904,5047,2023-12-13 22:39:54,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,True,False
905,5047,2023-12-13 22:42:34,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,True,False
906,5047,2023-12-13 22:45:14,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,True,False
907,5047,2023-12-13 22:47:54,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,True,False
908,5047,2023-12-13 22:50:34,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,True,False
909,5047,2023-12-13 22:53:14,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
910,5047,2023-12-13 22:56:53,3,1,220,53,31,125,20,44,0,0,31,125,20,44,0,0,False,True
911,5047,2023-12-13 22:58:59,0,0,126,19,25,37,20,44,0,0,25,37,20,44,0,0,False,True
912,5047,2023-12-13 23:01:14,3,2,135,154,25,46,20,44,0,0,25,46,20,44,0,0,False,True
913,5047,2023-12-13 23:03:54,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
914,5047,2023-12-13 23:06:34,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
915,5047,2023-12-13 23:09:14,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
987,5042,2023-12-13 23:26:52,0,0,160,92,34,58,29,18,13,8,34,58,29,18,13,8,False,False
988,5042,2023-12-13 23:29:32,0,0,160,92,34,58,29,18,13,8,34,58,29,18,13,8,False,False
989,5042,2023-12-13 23:32:12,0,0,160,92,34,58,29,18,13,8,34,58,29,18,13,8,True,False
990,5042,2023-12-13 23:34:22,0,0,130,112,33,31,29,16,13,8,33,31,29,16,13,8,True,True
991,5042,2023-12-13 23:36:32,0,0,130,92,33,31,29,16,13,8,33,31,29,16,13,8,True,True
992,5042,2023-12-13 23:38:53,0,0,141,83,33,42,29,16,13,8,33,42,29,16,13,8,True,True
993,5042,2023-12-13 23:41:23,0,0,150,83,33,51,29,16,13,8,33,51,29,16,13,8,True,False
994,5042,2023-12-13 23:43:53,0,0,150,83,33,51,29,16,13,8,33,51,29,16,13,8,True,False
995,5042,2023-12-13 23:46:23,0,0,150,83,33,51,29,16,13,8,33,51,29,16,13,8,True,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
852,5044,2023-12-13 16:59:00,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False
853,5044,2023-12-13 17:01:50,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,True,False
854,5044,2023-12-13 17:04:40,3,1,170,100,40,62,17,19,16,16,40,62,17,19,16,16,True,False
855,5044,2023-12-13 17:07:57,3,2,198,118,45,73,22,22,20,16,45,73,22,22,20,16,True,True
856,5044,2023-12-13 17:10:59,3,1,182,120,41,67,20,20,18,16,41,67,20,20,18,16,True,False
857,5044,2023-12-13 17:13:59,3,1,180,120,40,66,20,20,18,16,40,66,20,20,18,16,True,False
858,5044,2023-12-13 17:16:59,3,1,180,120,40,66,20,20,18,16,40,66,20,20,18,16,True,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1954,5033,2023-12-15 16:52:18,3,1,170,48,42,86,42,0,0,0,42,86,42,0,0,0,False,False
1955,5033,2023-12-15 16:55:08,3,1,170,48,42,86,42,0,0,0,42,86,42,0,0,0,False,False
1956,5033,2023-12-15 16:57:58,3,1,170,48,42,86,42,0,0,0,42,86,42,0,0,0,False,False
1957,5033,2023-12-15 23:59:30,3,1,130,51,36,14,27,27,26,0,36,14,27,27,26,0,False,True

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
923,5041,2023-12-13 20:28:54,3,1,180,114,46,113,11,10,0,0,46,113,11,10,0,0,False,False
924,5041,2023-12-13 20:31:54,3,1,180,115,46,113,11,10,0,0,46,113,11,10,0,0,True,False
925,5041,2023-12-13 20:34:53,3,1,179,143,46,112,11,10,0,0,46,112,11,10,0,0,True,False
926,5041,2023-12-13 20:37:16,3,2,143,116,46,77,10,10,0,0,46,77,10,10,0,0,True,True
927,5041,2023-12-13 20:39:54,3,2,158,104,46,92,10,10,0,0,46,92,10,10,0,0,True,False
928,5041,2023-12-13 20:42:44,3,1,170,104,46,103,11,10,0,0,46,103,11,10,0,0,True,False
929,5041,2023-12-13 20:45:34,3,1,170,105,46,103,11,10,0,0,46,103,11,10,0,0,True,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1559,5045,2023-12-15 05:56:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
1560,5045,2023-12-15 05:59:54,0,0,180,175,27,81,36,36,0,0,27,81,36,36,0,0,False,False
1561,5045,2023-12-15 06:02:54,0,0,180,175,27,81,36,36,0,0,27,81,36,36,0,0,True,False
1562,5045,2023-12-15 06:06:43,0,0,229,3,41,112,37,39,0,0,27,126,37,39,0,0,True,True
1563,5045,2023-12-15 06:10:23,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,True,False
1564,5045,2023-12-15 06:14:03,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,True,False
1565,5045,2023-12-15 06:17:43,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,True,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
437,5034,2023-12-12 20:56:37,3,1,180,158,57,33,45,45,0,0,31,59,45,45,0,0,False,False
438,5034,2023-12-12 20:59:38,3,1,180,158,57,33,45,45,0,0,31,59,45,45,0,0,False,False
439,5034,2023-12-12 21:02:38,3,1,180,108,57,33,45,45,0,0,31,59,45,45,0,0,True,False
440,5034,2023-12-12 21:06:17,3,2,219,157,65,39,58,57,0,0,37,67,58,57,0,0,True,True
441,5034,2023-12-12 21:09:07,3,1,170,157,51,30,45,44,0,0,29,52,45,44,0,0,True,False
442,5034,2023-12-12 21:11:57,3,1,170,157,51,30,45,44,0,0,29,52,45,44,0,0,True,False
443,5034,2023-12-12 21:14:46,3,1,170,157,51,30,45,44,0,0,29,52,45,44,0,0,True,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
628,5034,2023-12-13 05:09:46,3,1,150,135,43,21,43,43,0,0,21,43,43,43,0,0,False,False
629,5034,2023-12-13 05:12:16,3,1,150,135,43,21,43,43,0,0,21,43,43,43,0,0,False,False
630,5034,2023-12-13 05:14:46,3,1,150,135,43,21,43,43,0,0,21,43,43,43,0,0,False,False
631,5034,2023-12-13 05:16:54,3,1,105,135,43,21,41,0,0,0,21,43,41,0,0,0,False,True
632,5034,2023-12-13 05:17:38,0,0,67,8,0,0,0,67,0,0,0,0,0,67,0,0,False,True
633,5034,2023-12-13 05:20:08,0,0,150,7,43,21,43,43,0,0,21,43,43,43,0,0,False,False
634,5034,2023-12-13 05:22:36,3,2,150,7,43,21,43,43,0,0,21,43,43,43,0,0,False,False
635,5034,2023-12-13 05:25:07,3,2,150,7,43,21,43,43,0,0,21,43,43,43,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1508,5046,2023-12-15 03:10:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1509,5046,2023-12-15 03:12:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1510,5046,2023-12-15 03:15:10,0,0,151,9,24,42,43,42,0,0,24,42,43,42,0,0,False,False
1511,5046,2023-12-15 03:17:38,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1512,5046,2023-12-15 03:20:08,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1513,5046,2023-12-15 03:22:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1514,5046,2023-12-15 03:25:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

In [8]:
"""
5. 전이시간 바깥에서 발생하는 이상현시시간 관찰

이상치존재가 True이고 전이시간여부가 False인 경우에 대하여 앞의 두 번 뒤의 두 번을 포함해 관찰합니다.
"""

infos['context_dfs_outside_the_transition_ranges'] = {}
infos['outlier_lists'] = {}
infos['outliers'] = []
for inter_no in inter_nos:
    dfs = infos['context_dfs_list'][inter_no]
    dfs = [dfs[i] for i in range(len(dfs)) if ~dfs[i].iloc[2]['전이시간여부']]
    infos['context_dfs_outside_the_transition_ranges'][inter_no] = pd.concat(dfs).drop_duplicates()

    df = infos['outlier_dfs'][inter_no].iloc[:,6:-2]
    is_outlier = df.isin(infos['unaccepted_durations'][inter_no])
    temp = df[is_outlier].values.flatten()
    temp = np.unique(temp[pd.notna(temp)])
    infos['outlier_lists'][inter_no] = np.unique(temp[pd.notna(temp)])
    infos['outliers'].extend(infos['outlier_lists'][inter_no])

In [9]:
def display_context_dfs_outside_the_transition_ranges(inter_no):
    DF = infos['context_dfs_outside_the_transition_ranges'][inter_no]
    dfs = []
    temp = []
    for i in DF.index:
        if not temp or i == temp[-1] + 1:
            temp.append(i)
        else:
            dfs.append(DF.loc[temp])
            temp = [i]
    if temp:
        dfs.append(DF.loc[temp])
    for df in dfs:
        display(df)
    # return dfs

In [10]:
for inter_no in inter_nos:
    display_context_dfs_outside_the_transition_ranges(inter_no)

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
775,5031,2023-12-13 10:29:00,3,1,160,140,49,20,27,29,35,0,49,20,27,29,35,0,False,False
776,5031,2023-12-13 10:31:40,3,1,160,140,49,20,27,29,35,0,49,20,27,29,35,0,False,False
777,5031,2023-12-13 10:34:20,3,1,160,140,49,20,27,29,35,0,49,20,27,29,35,0,False,False
778,5031,2023-12-13 10:39:07,3,1,31,107,49,20,27,156,35,0,49,20,27,156,35,0,False,True
779,5031,2023-12-13 10:41:27,0,0,140,87,37,16,27,25,35,0,37,16,27,25,35,0,False,False
780,5031,2023-12-13 10:45:00,3,2,213,140,69,31,31,43,39,0,69,31,31,43,39,0,False,True
781,5031,2023-12-13 10:47:40,3,1,160,140,49,20,27,29,35,0,49,20,27,29,35,0,False,False
782,5031,2023-12-13 10:50:20,3,1,160,140,49,20,27,29,35,0,49,20,27,29,35,0,False,False
783,5031,2023-12-13 10:53:00,3,1,160,140,49,20,27,29,35,0,49,20,27,29,35,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
909,5031,2023-12-13 17:59:38,3,1,180,159,65,20,27,33,35,0,65,20,27,33,35,0,False,False
910,5031,2023-12-13 18:02:38,3,1,180,159,65,20,27,33,35,0,65,20,27,33,35,0,False,False
911,5031,2023-12-13 18:05:38,3,1,180,159,65,20,27,33,35,0,65,20,27,33,35,0,False,False
912,5031,2023-12-13 18:10:47,3,1,52,107,65,20,27,161,35,0,65,20,27,161,35,0,False,True
913,5031,2023-12-13 18:13:07,0,0,140,67,37,16,27,25,35,0,37,16,27,25,35,0,False,False
914,5031,2023-12-13 18:17:06,3,2,239,126,90,31,31,48,39,0,90,31,31,48,39,0,False,True
915,5031,2023-12-13 18:20:39,3,2,213,159,78,25,31,40,39,0,78,25,31,40,39,0,False,True
916,5031,2023-12-13 18:23:39,3,1,180,160,65,20,27,33,35,0,65,20,27,33,35,0,False,False
917,5031,2023-12-13 18:26:38,3,1,179,159,65,20,27,32,35,0,65,20,27,32,35,0,False,False
918,5031,2023-12-13 18:29:38,3,1,180,158,65,20,27,33,35,0,65,20,27,33,35,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1763,5031,2023-12-15 07:21:58,0,0,1,58,126,35,27,34,35,0,126,35,27,34,35,0,False,True
1764,5031,2023-12-15 07:24:18,0,0,140,19,37,16,27,25,35,0,37,16,27,25,35,0,False,False
1765,5031,2023-12-15 07:26:49,3,2,151,169,39,25,27,25,35,0,39,25,27,25,35,0,False,False
1766,5031,2023-12-15 07:29:41,3,2,172,161,47,32,27,31,35,0,47,32,27,31,35,0,False,True
1767,5031,2023-12-15 07:32:41,3,1,180,161,49,35,27,34,35,0,49,35,27,34,35,0,False,False
1768,5031,2023-12-15 07:35:41,3,1,180,161,49,35,27,34,35,0,49,35,27,34,35,0,False,False
1769,5031,2023-12-15 07:38:41,3,1,180,161,49,35,27,34,35,0,49,35,27,34,35,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
0,5032,2023-12-12 00:00:40,3,1,140,40,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1,5032,2023-12-12 00:03:20,3,2,160,60,25,51,24,37,23,0,25,51,24,37,23,0,False,True
2,5032,2023-12-12 00:05:40,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
3,5032,2023-12-12 00:08:00,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
4,5032,2023-12-12 00:10:20,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
189,5032,2023-12-12 07:34:15,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
190,5032,2023-12-12 07:37:05,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
191,5032,2023-12-12 07:39:55,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
192,5032,2023-12-12 07:42:27,3,1,133,37,0,55,21,37,20,0,0,55,21,37,20,0,False,True
193,5032,2023-12-12 07:44:24,0,0,117,154,18,24,19,37,19,0,18,24,19,37,19,0,False,True
194,5032,2023-12-12 07:48:10,3,2,226,40,35,84,35,37,35,0,35,84,35,37,35,0,False,True
195,5032,2023-12-12 07:51:15,3,2,185,55,27,67,27,37,27,0,27,67,27,37,27,0,False,False
196,5032,2023-12-12 07:54:05,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
197,5032,2023-12-12 07:56:55,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
520,5032,2023-12-12 23:55:59,3,1,139,59,20,43,20,37,19,0,20,43,20,37,19,0,False,False
521,5032,2023-12-12 23:58:20,3,1,141,60,21,43,20,37,20,0,21,43,20,37,20,0,False,False
522,5032,2023-12-13 00:00:40,3,1,140,40,20,43,20,37,20,0,20,43,20,37,20,0,False,False
523,5032,2023-12-13 00:03:20,3,2,160,61,25,51,24,37,23,0,25,51,24,37,23,0,False,True
524,5032,2023-12-13 00:05:40,3,1,139,60,20,43,20,37,19,0,20,43,20,37,19,0,False,False
525,5032,2023-12-13 00:08:00,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
526,5032,2023-12-13 00:10:20,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
654,5032,2023-12-13 05:09:01,3,1,140,61,20,43,20,37,20,0,20,43,20,37,20,0,False,False
655,5032,2023-12-13 05:11:20,3,1,139,60,20,43,20,37,19,0,20,43,20,37,19,0,False,False
656,5032,2023-12-13 05:13:40,3,1,141,60,20,43,20,38,20,0,20,43,20,38,20,0,False,False
657,5032,2023-12-13 05:17:53,0,0,252,32,132,43,20,37,20,0,132,43,20,37,20,0,False,True
658,5032,2023-12-13 05:19:50,0,0,117,9,18,24,19,37,19,0,18,24,19,37,19,0,False,True
659,5032,2023-12-13 05:22:55,3,2,186,55,30,60,30,37,29,0,30,60,30,37,29,0,False,True
660,5032,2023-12-13 05:25:20,3,2,145,60,21,45,21,37,21,0,21,45,21,37,21,0,False,True
661,5032,2023-12-13 05:27:40,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
662,5032,2023-12-13 05:30:00,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
663,5032,2023-12-13 05:32:20,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
716,5032,2023-12-13 07:51:15,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
717,5032,2023-12-13 07:54:05,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
718,5032,2023-12-13 07:56:37,3,1,132,38,0,54,22,37,19,0,0,54,22,37,19,0,False,False
719,5032,2023-12-13 07:58:34,0,0,117,155,18,24,19,37,19,0,18,24,19,37,19,0,False,True
720,5032,2023-12-13 08:02:20,3,2,226,41,35,84,35,37,35,0,35,84,35,37,35,0,False,True
721,5032,2023-12-13 08:05:24,3,2,184,55,27,67,27,37,26,0,27,67,27,37,26,0,False,False
722,5032,2023-12-13 08:08:14,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
723,5032,2023-12-13 08:11:05,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
892,5032,2023-12-13 17:33:58,3,1,180,58,24,67,26,37,26,0,24,67,26,37,26,0,False,False
893,5032,2023-12-13 17:36:58,3,1,180,58,24,67,26,37,26,0,24,67,26,37,26,0,False,False
894,5032,2023-12-13 17:39:58,3,1,180,58,24,67,26,37,26,0,24,67,26,37,26,0,False,False
895,5032,2023-12-13 17:43:18,0,0,200,79,24,87,26,37,26,0,24,87,26,37,26,0,False,True
896,5032,2023-12-13 17:45:57,0,0,159,58,28,34,30,37,30,0,28,34,30,37,30,0,False,True
897,5032,2023-12-13 17:48:57,3,1,180,58,24,67,26,37,26,0,24,67,26,37,26,0,False,False
898,5032,2023-12-13 17:51:57,3,1,180,58,24,67,26,37,26,0,24,67,26,37,26,0,False,False
899,5032,2023-12-13 17:54:57,3,1,180,58,24,67,26,37,26,0,24,67,26,37,26,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1028,5032,2023-12-13 23:56:00,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1029,5032,2023-12-13 23:58:20,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1030,5032,2023-12-14 00:00:41,3,1,140,40,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1031,5032,2023-12-14 00:03:20,3,2,160,60,25,51,24,37,23,0,25,51,24,37,23,0,False,True
1032,5032,2023-12-14 00:05:41,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1033,5032,2023-12-14 00:08:00,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1034,5032,2023-12-14 00:10:20,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1229,5032,2023-12-14 08:02:34,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
1230,5032,2023-12-14 08:05:24,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
1231,5032,2023-12-14 08:08:15,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
1232,5032,2023-12-14 08:11:05,3,1,133,55,0,55,22,37,19,0,0,55,22,37,19,0,False,True
1233,5032,2023-12-14 08:13:55,0,0,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
1234,5032,2023-12-14 08:16:45,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
1235,5032,2023-12-14 08:19:35,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1565,5032,2023-12-14 23:53:40,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1566,5032,2023-12-14 23:56:00,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1567,5032,2023-12-14 23:58:20,3,1,140,60,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1568,5032,2023-12-14 23:59:46,3,1,131,67,33,34,30,34,0,0,33,34,30,34,0,0,False,True
1569,5032,2023-12-15 00:00:41,3,1,140,40,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1570,5032,2023-12-15 00:03:21,3,2,160,60,25,51,24,37,23,0,25,51,24,37,23,0,False,True
1571,5032,2023-12-15 00:05:40,3,1,140,61,20,43,20,37,20,0,20,43,20,37,20,0,False,False
1572,5032,2023-12-15 00:08:00,3,1,139,60,20,43,20,37,19,0,20,43,20,37,19,0,False,False
1573,5032,2023-12-15 00:10:20,3,1,140,59,20,43,20,37,20,0,20,43,20,37,20,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1955,5032,2023-12-15 16:52:24,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
1956,5032,2023-12-15 16:55:14,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
1957,5032,2023-12-15 16:58:04,3,1,170,55,24,61,24,37,24,0,24,61,24,37,24,0,False,False
1958,5032,2023-12-15 23:59:30,3,1,130,51,36,14,27,27,26,0,36,14,27,27,26,0,False,True

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
0,5033,2023-12-12 00:00:32,3,1,140,32,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1,5033,2023-12-12 00:03:12,3,2,160,52,48,71,41,0,0,0,48,71,41,0,0,0,False,True
2,5033,2023-12-12 00:05:32,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
3,5033,2023-12-12 00:07:52,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
4,5033,2023-12-12 00:10:12,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
520,5033,2023-12-12 23:55:51,3,1,139,51,42,62,35,0,0,0,42,62,35,0,0,0,False,False
521,5033,2023-12-12 23:58:12,3,1,141,52,43,62,36,0,0,0,43,62,36,0,0,0,False,False
522,5033,2023-12-13 00:00:33,3,1,140,32,42,62,36,0,0,0,42,62,36,0,0,0,False,False
523,5033,2023-12-13 00:03:12,3,2,160,53,48,71,41,0,0,0,48,71,41,0,0,0,False,True
524,5033,2023-12-13 00:05:31,3,1,139,52,42,62,35,0,0,0,42,62,35,0,0,0,False,False
525,5033,2023-12-13 00:07:52,3,1,140,51,42,62,36,0,0,0,42,62,36,0,0,0,False,False
526,5033,2023-12-13 00:10:12,3,1,141,52,43,62,36,0,0,0,43,62,36,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
654,5033,2023-12-13 05:08:53,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
655,5033,2023-12-13 05:11:13,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
656,5033,2023-12-13 05:13:33,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
657,5033,2023-12-13 05:16:57,3,1,204,116,42,126,36,0,0,0,42,126,36,0,0,0,False,True
658,5033,2023-12-13 05:18:56,0,0,119,95,42,53,24,0,0,0,42,53,24,0,0,0,False,True
659,5033,2023-12-13 05:20:55,3,2,119,74,42,53,24,0,0,0,42,53,24,0,0,0,False,True
660,5033,2023-12-13 05:22:53,3,2,119,53,42,53,24,0,0,0,42,53,24,0,0,0,False,True
661,5033,2023-12-13 05:25:12,3,1,139,52,42,62,35,0,0,0,42,62,35,0,0,0,False,False
662,5033,2023-12-13 05:27:32,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
663,5033,2023-12-13 05:29:52,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
892,5033,2023-12-13 17:30:43,3,1,180,44,42,94,44,0,0,0,42,94,44,0,0,0,False,False
893,5033,2023-12-13 17:33:43,3,1,180,44,42,94,44,0,0,0,42,94,44,0,0,0,False,False
894,5033,2023-12-13 17:36:43,3,1,180,44,42,94,44,0,0,0,42,94,44,0,0,0,False,False
895,5033,2023-12-13 17:42:34,3,1,94,34,42,94,214,0,0,0,42,94,214,0,0,0,False,True
896,5033,2023-12-13 17:44:33,0,0,119,153,42,53,24,0,0,0,42,53,24,0,0,0,False,True
897,5033,2023-12-13 17:48:32,3,2,239,32,54,126,59,0,0,0,54,126,59,0,0,0,False,True
898,5033,2023-12-13 17:51:44,3,2,192,44,45,100,47,0,0,0,45,100,47,0,0,0,False,True
899,5033,2023-12-13 17:54:44,3,1,180,44,42,94,44,0,0,0,42,94,44,0,0,0,False,False
900,5033,2023-12-13 17:57:44,3,1,180,44,42,94,44,0,0,0,42,94,44,0,0,0,False,False
901,5033,2023-12-13 18:00:44,3,1,180,44,42,94,44,0,0,0,42,94,44,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1028,5033,2023-12-13 23:55:52,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1029,5033,2023-12-13 23:58:12,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1030,5033,2023-12-14 00:00:32,3,1,140,32,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1031,5033,2023-12-14 00:03:12,3,2,160,52,48,71,41,0,0,0,48,71,41,0,0,0,False,True
1032,5033,2023-12-14 00:05:32,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1033,5033,2023-12-14 00:07:52,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1034,5033,2023-12-14 00:10:12,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1565,5033,2023-12-14 23:53:32,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1566,5033,2023-12-14 23:55:52,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1567,5033,2023-12-14 23:58:12,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1568,5033,2023-12-14 23:59:46,3,1,131,67,33,34,30,34,0,0,33,34,30,34,0,0,False,True
1569,5033,2023-12-15 00:00:32,3,1,140,32,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1570,5033,2023-12-15 00:03:13,3,2,160,52,48,71,41,0,0,0,48,71,41,0,0,0,False,True
1571,5033,2023-12-15 00:05:32,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1572,5033,2023-12-15 00:07:52,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1573,5033,2023-12-15 00:10:12,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1582,5033,2023-12-15 00:31:12,3,1,141,53,43,62,36,0,0,0,43,62,36,0,0,0,False,False
1583,5033,2023-12-15 00:33:31,3,1,139,52,42,62,35,0,0,0,42,62,35,0,0,0,False,False
1584,5033,2023-12-15 00:35:52,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1585,5033,2023-12-15 00:39:32,3,1,220,132,42,142,36,0,0,0,42,142,36,0,0,0,False,True
1586,5033,2023-12-15 00:41:31,0,0,119,111,42,53,24,0,0,0,42,53,24,0,0,0,False,True
1587,5033,2023-12-15 00:44:37,3,2,186,17,54,83,49,0,0,0,54,83,49,0,0,0,False,True
1588,5033,2023-12-15 00:47:32,3,2,175,52,53,78,44,0,0,0,53,78,44,0,0,0,False,True
1589,5033,2023-12-15 00:49:52,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1590,5033,2023-12-15 00:52:12,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False
1591,5033,2023-12-15 00:54:32,3,1,140,52,42,62,36,0,0,0,42,62,36,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1954,5033,2023-12-15 16:52:18,3,1,170,48,42,86,42,0,0,0,42,86,42,0,0,0,False,False
1955,5033,2023-12-15 16:55:08,3,1,170,48,42,86,42,0,0,0,42,86,42,0,0,0,False,False
1956,5033,2023-12-15 16:57:58,3,1,170,48,42,86,42,0,0,0,42,86,42,0,0,0,False,False
1957,5033,2023-12-15 23:59:30,3,1,130,51,36,14,27,27,26,0,36,14,27,27,26,0,False,True

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
385,5034,2023-12-12 18:19:05,0,0,57,65,57,0,0,0,0,0,31,0,0,0,0,0,False,False
386,5034,2023-12-12 18:22:05,0,0,180,65,57,33,45,45,0,0,31,59,45,45,0,0,False,False
387,5034,2023-12-12 18:24:35,0,0,150,35,43,21,43,43,0,0,21,43,43,43,0,0,False,False
388,5034,2023-12-12 18:28:35,3,2,240,95,76,44,60,60,0,0,41,79,60,60,0,0,False,True
389,5034,2023-12-12 18:32:35,3,2,240,155,76,44,60,60,0,0,41,79,60,60,0,0,False,True
390,5034,2023-12-12 18:35:39,3,1,184,159,58,34,46,46,0,0,32,60,46,46,0,0,False,False
391,5034,2023-12-12 18:38:39,3,1,180,159,57,33,45,45,0,0,31,59,45,45,0,0,False,False
392,5034,2023-12-12 18:41:39,3,1,180,159,57,33,45,45,0,0,31,59,45,45,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
628,5034,2023-12-13 05:09:46,3,1,150,135,43,21,43,43,0,0,21,43,43,43,0,0,False,False
629,5034,2023-12-13 05:12:16,3,1,150,135,43,21,43,43,0,0,21,43,43,43,0,0,False,False
630,5034,2023-12-13 05:14:46,3,1,150,135,43,21,43,43,0,0,21,43,43,43,0,0,False,False
631,5034,2023-12-13 05:16:54,3,1,105,135,43,21,41,0,0,0,21,43,41,0,0,0,False,True
632,5034,2023-12-13 05:17:38,0,0,67,8,0,0,0,67,0,0,0,0,0,67,0,0,False,True
633,5034,2023-12-13 05:20:08,0,0,150,7,43,21,43,43,0,0,21,43,43,43,0,0,False,False
634,5034,2023-12-13 05:22:36,3,2,150,7,43,21,43,43,0,0,21,43,43,43,0,0,False,False
635,5034,2023-12-13 05:25:07,3,2,150,7,43,21,43,43,0,0,21,43,43,43,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
683,5034,2023-12-13 07:41:40,0,3,180,160,53,33,51,43,0,0,26,60,51,43,0,0,False,False
684,5034,2023-12-13 07:44:40,0,3,180,160,53,33,51,43,0,0,26,60,51,43,0,0,False,False
685,5034,2023-12-13 07:47:30,0,3,130,160,53,33,44,0,0,0,26,60,44,0,0,0,False,False
686,5034,2023-12-13 07:48:15,0,3,130,16,0,0,44,86,0,0,0,0,44,86,0,0,False,True
687,5034,2023-12-13 07:50:58,0,3,162,178,45,28,46,43,0,0,22,51,46,43,0,0,False,False
688,5034,2023-12-13 07:53:39,0,3,162,160,45,28,46,43,0,0,22,51,46,43,0,0,False,False
689,5034,2023-12-13 07:56:39,0,3,180,160,53,33,51,43,0,0,26,60,51,43,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
707,5034,2023-12-13 08:50:40,0,3,180,160,53,33,51,43,0,0,26,60,51,43,0,0,False,False
708,5034,2023-12-13 08:53:40,0,3,180,160,53,33,51,43,0,0,26,60,51,43,0,0,False,False
709,5034,2023-12-13 08:59:12,0,3,46,132,0,0,0,46,0,0,0,0,0,46,0,0,False,False
710,5034,2023-12-13 09:02:40,0,3,208,160,61,39,59,49,0,0,30,70,59,49,0,0,False,True
711,5034,2023-12-13 09:05:40,0,3,180,160,53,33,51,43,0,0,26,60,51,43,0,0,False,False
712,5034,2023-12-13 09:08:40,0,3,180,160,53,33,51,43,0,0,26,60,51,43,0,0,False,False
713,5034,2023-12-13 09:11:40,0,3,180,160,53,33,51,43,0,0,26,60,51,43,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
730,5034,2023-12-13 10:00:27,3,1,170,157,51,33,43,43,0,0,27,57,43,43,0,0,False,False
731,5034,2023-12-13 10:03:17,3,1,170,157,51,33,43,43,0,0,27,57,43,43,0,0,False,False
732,5034,2023-12-13 10:06:07,3,1,170,157,51,33,43,43,0,0,27,57,43,43,0,0,False,False
733,5034,2023-12-13 10:08:55,3,1,168,156,51,33,43,41,0,0,27,57,43,41,0,0,False,True
734,5034,2023-12-13 10:12:42,0,0,106,42,0,0,53,53,0,0,0,71,53,53,0,0,False,True
735,5034,2023-12-13 10:16:11,0,0,209,81,63,41,53,52,0,0,34,70,53,52,0,0,False,True
736,5034,2023-12-13 10:18:40,0,0,150,61,43,21,43,43,0,0,21,43,43,43,0,0,False,False
737,5034,2023-12-13 10:22:26,3,2,226,117,68,44,57,57,0,0,36,76,57,57,0,0,False,True
738,5034,2023-12-13 10:25:57,3,2,210,157,63,41,53,53,0,0,33,71,53,53,0,0,False,True
739,5034,2023-12-13 10:28:47,3,1,170,157,51,33,43,43,0,0,27,57,43,43,0,0,False,False
740,5034,2023-12-13 10:31:37,3,1,170,157,51,33,43,43,0,0,27,57,43,43,0,0,False,False
741,5034,2023-12-13 10:34:27,3,1,170,157,51,33,43,43,0,0,27,57,43,43,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
865,5034,2023-12-13 17:42:38,0,0,57,38,57,0,0,0,0,0,31,0,0,0,0,0,False,False
866,5034,2023-12-13 17:45:38,0,0,180,39,57,33,45,45,0,0,31,59,45,45,0,0,False,False
867,5034,2023-12-13 17:48:08,0,0,150,8,43,21,43,43,0,0,21,43,43,43,0,0,False,False
868,5034,2023-12-13 17:52:08,3,2,240,68,76,44,60,60,0,0,41,79,60,60,0,0,False,True
869,5034,2023-12-13 17:56:08,3,2,240,128,76,44,60,60,0,0,41,79,60,60,0,0,False,True
870,5034,2023-12-13 17:59:38,3,2,210,159,67,38,53,52,0,0,36,69,53,52,0,0,False,True
871,5034,2023-12-13 18:02:38,3,1,180,159,57,33,45,45,0,0,31,59,45,45,0,0,False,False
872,5034,2023-12-13 18:05:38,3,1,180,159,57,33,45,45,0,0,31,59,45,45,0,0,False,False
873,5034,2023-12-13 18:08:38,3,1,180,159,57,33,45,45,0,0,31,59,45,45,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
943,5034,2023-12-13 21:37:27,3,1,170,157,51,30,45,44,0,0,29,52,45,44,0,0,False,False
944,5034,2023-12-13 21:40:17,3,1,170,157,51,30,45,44,0,0,29,52,45,44,0,0,False,False
945,5034,2023-12-13 21:43:07,3,1,124,157,51,30,43,0,0,0,29,52,43,0,0,0,False,False
946,5034,2023-12-13 21:43:51,0,0,90,32,0,0,0,90,0,0,0,0,0,90,0,0,False,True
947,5034,2023-12-13 21:46:21,0,0,150,11,43,21,43,43,0,0,21,43,43,43,0,0,False,False
948,5034,2023-12-13 21:48:51,3,2,150,161,43,21,43,43,0,0,21,43,43,43,0,0,False,False
949,5034,2023-12-13 21:51:37,3,2,166,157,50,29,44,43,0,0,28,51,44,43,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1204,5034,2023-12-14 09:05:38,3,1,180,158,53,33,51,43,0,0,26,60,51,43,0,0,False,False
1205,5034,2023-12-14 09:10:40,3,1,43,100,0,0,0,43,0,0,0,0,0,43,0,0,False,False
1206,5034,2023-12-14 09:13:09,0,0,150,69,43,21,43,43,0,0,21,43,43,43,0,0,False,False
1207,5034,2023-12-14 09:17:08,3,2,239,128,70,44,68,57,0,0,34,80,68,57,0,0,False,True
1208,5034,2023-12-14 09:20:38,3,2,210,158,62,38,60,50,0,0,30,70,60,50,0,0,False,True
1209,5034,2023-12-14 09:23:38,3,1,180,159,53,33,51,43,0,0,26,60,51,43,0,0,False,False
1210,5034,2023-12-14 09:26:37,3,1,179,157,53,33,50,43,0,0,26,60,50,43,0,0,False,False
1211,5034,2023-12-14 09:29:38,3,1,181,159,53,33,52,43,0,0,26,60,52,43,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1354,5034,2023-12-14 16:12:59,0,0,51,68,51,0,0,0,0,0,27,0,0,0,0,0,False,False
1355,5034,2023-12-14 16:15:49,0,0,170,69,51,33,43,43,0,0,27,57,43,43,0,0,False,False
1356,5034,2023-12-14 16:18:19,0,0,150,48,43,21,43,43,0,0,21,43,43,43,0,0,False,False
1357,5034,2023-12-14 16:22:05,3,2,226,104,68,44,57,57,0,0,36,76,57,57,0,0,False,True
1358,5034,2023-12-14 16:25:48,3,2,223,157,67,43,57,56,0,0,35,75,57,56,0,0,False,True
1359,5034,2023-12-14 16:28:38,3,1,170,158,51,33,43,43,0,0,27,57,43,43,0,0,False,False
1360,5034,2023-12-14 16:31:27,3,1,169,156,50,33,43,43,0,0,27,56,43,43,0,0,False,False
1361,5034,2023-12-14 16:34:18,3,1,171,158,51,33,44,43,0,0,27,57,44,43,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1409,5034,2023-12-14 18:56:37,3,1,180,158,57,33,45,45,0,0,31,59,45,45,0,0,False,False
1410,5034,2023-12-14 18:59:37,3,1,180,158,57,33,45,45,0,0,31,59,45,45,0,0,False,False
1411,5034,2023-12-14 19:02:18,3,1,135,158,57,33,45,0,0,0,31,59,45,0,0,0,False,False
1412,5034,2023-12-14 19:03:04,0,0,71,4,0,0,0,71,0,0,0,0,0,71,0,0,False,True
1413,5034,2023-12-14 19:05:37,0,0,154,158,43,25,43,43,0,0,23,45,43,43,0,0,False,False
1414,5034,2023-12-14 19:08:37,3,1,180,157,57,33,45,45,0,0,31,59,45,45,0,0,False,False
1415,5034,2023-12-14 19:11:39,3,1,182,160,58,33,46,45,0,0,31,60,46,45,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1727,5034,2023-12-15 09:17:37,3,1,180,158,53,33,51,43,0,0,26,60,51,43,0,0,False,False
1728,5034,2023-12-15 09:22:34,3,1,112,95,0,0,61,51,0,0,0,0,61,51,0,0,False,False
1729,5034,2023-12-15 09:25:04,0,0,150,64,43,21,43,43,0,0,21,43,43,43,0,0,False,False
1730,5034,2023-12-15 09:29:03,3,2,239,123,70,44,68,57,0,0,34,80,68,57,0,0,False,True
1731,5034,2023-12-15 09:32:38,3,2,215,18,63,40,61,51,0,0,31,72,61,51,0,0,True,True
1732,5034,2023-12-15 09:35:08,3,2,150,168,43,21,43,43,0,0,21,43,43,43,0,0,True,False
1733,5034,2023-12-15 09:37:48,3,2,159,157,44,29,43,43,0,0,23,50,43,43,0,0,True,False
1734,5034,2023-12-15 09:40:38,3,1,170,157,51,33,43,43,0,0,27,57,43,43,0,0,True,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
797,5035,2023-12-13 13:10:09,3,1,170,149,61,31,39,39,0,0,35,57,39,39,0,0,False,False
798,5035,2023-12-13 13:12:59,3,1,170,149,61,31,39,39,0,0,35,57,39,39,0,0,False,False
799,5035,2023-12-13 13:15:50,3,1,170,149,61,31,39,39,0,0,35,57,39,39,0,0,False,False
800,5035,2023-12-13 13:20:52,3,1,46,111,61,163,39,39,0,0,35,189,39,39,0,0,False,True
801,5035,2023-12-13 13:24:20,3,2,208,150,75,38,48,47,0,0,43,70,48,47,0,0,False,True
802,5035,2023-12-13 13:27:09,3,1,169,149,60,31,39,39,0,0,35,56,39,39,0,0,False,False
803,5035,2023-12-13 13:29:59,3,1,170,149,61,31,39,39,0,0,35,57,39,39,0,0,False,False
804,5035,2023-12-13 13:32:48,3,1,170,148,61,31,39,39,0,0,35,57,39,39,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
906,5035,2023-12-13 19:53:26,3,1,180,146,64,33,39,44,0,0,34,63,39,44,0,0,False,False
907,5035,2023-12-13 19:56:25,3,1,180,146,64,33,39,44,0,0,34,63,39,44,0,0,False,False
908,5035,2023-12-13 19:59:25,3,1,180,146,64,33,39,44,0,0,34,63,39,44,0,0,False,False
909,5035,2023-12-13 20:03:23,3,1,238,23,64,91,39,44,0,0,34,121,39,44,0,0,False,True
910,5035,2023-12-13 20:05:54,3,2,151,174,53,28,33,37,0,0,28,53,33,37,0,0,False,False
911,5035,2023-12-13 20:08:25,3,2,152,145,54,28,33,37,0,0,29,53,33,37,0,0,False,True
912,5035,2023-12-13 20:11:26,3,1,181,146,65,33,39,44,0,0,34,64,39,44,0,0,False,False
913,5035,2023-12-13 20:14:27,3,1,180,146,64,33,39,44,0,0,34,63,39,44,0,0,False,False
914,5035,2023-12-13 20:17:26,3,1,180,146,64,33,39,44,0,0,34,63,39,44,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
992,5035,2023-12-13 23:52:29,3,1,151,149,57,28,33,33,0,0,28,57,33,33,0,0,False,False
993,5035,2023-12-13 23:54:59,3,1,150,149,56,28,33,33,0,0,28,56,33,33,0,0,False,False
994,5035,2023-12-13 23:57:30,3,1,150,149,56,28,33,33,0,0,28,56,33,33,0,0,False,False
995,5035,2023-12-13 23:59:56,3,1,131,76,26,45,25,35,0,0,26,45,25,35,0,0,False,True
996,5035,2023-12-13 23:59:59,3,1,150,149,56,28,33,33,0,0,28,56,33,33,0,0,False,False
997,5035,2023-12-14 00:02:30,3,1,150,149,56,28,33,33,0,0,28,56,33,33,0,0,False,False
998,5035,2023-12-14 00:04:59,3,1,150,148,56,28,33,33,0,0,28,56,33,33,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1290,5036,2023-12-14 13:01:03,3,1,170,113,37,46,25,30,32,0,37,46,25,30,32,0,False,False
1291,5036,2023-12-14 13:03:53,3,1,170,113,37,46,25,30,32,0,37,46,25,30,32,0,False,False
1292,5036,2023-12-14 13:06:30,3,1,170,100,37,46,25,30,32,0,37,46,25,30,32,0,False,False
1293,5036,2023-12-14 13:09:29,3,2,179,109,26,54,31,30,38,0,26,54,31,30,38,0,False,True
1294,5036,2023-12-14 13:12:22,3,2,173,112,38,47,26,30,32,0,38,47,26,30,32,0,False,False
1295,5036,2023-12-14 13:15:13,3,1,171,113,38,46,25,30,32,0,38,46,25,30,32,0,False,False
1296,5036,2023-12-14 13:18:03,3,1,170,113,37,46,25,30,32,0,37,46,25,30,32,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
0,5037,2023-12-12 00:01:47,3,1,140,107,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1,5037,2023-12-12 00:04:27,3,2,160,128,43,51,34,32,0,0,43,51,34,32,0,0,False,True
2,5037,2023-12-12 00:06:47,3,1,139,127,37,45,29,28,0,0,37,45,29,28,0,0,False,False
3,5037,2023-12-12 00:09:06,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False
4,5037,2023-12-12 00:11:26,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
264,5037,2023-12-12 11:46:24,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
265,5037,2023-12-12 11:49:04,3,1,160,144,37,63,32,28,0,0,37,63,32,28,0,0,False,False
266,5037,2023-12-12 11:51:42,3,1,159,142,37,63,31,28,0,0,37,63,31,28,0,0,False,False
267,5037,2023-12-12 11:53:54,3,1,104,114,0,49,27,28,0,0,0,49,27,28,0,0,False,True
268,5037,2023-12-12 11:55:52,0,0,118,72,37,33,20,28,0,0,37,33,20,28,0,0,False,True
269,5037,2023-12-12 11:59:25,3,2,213,125,49,84,43,37,0,0,49,84,43,37,0,0,False,True
270,5037,2023-12-12 12:02:23,3,2,178,143,41,70,36,31,0,0,41,70,36,31,0,0,False,True
271,5037,2023-12-12 12:05:03,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
272,5037,2023-12-12 12:07:43,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
273,5037,2023-12-12 12:10:23,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
534,5037,2023-12-12 23:57:07,3,1,139,127,37,45,29,28,0,0,37,45,29,28,0,0,False,False
535,5037,2023-12-12 23:59:26,3,1,140,126,37,45,30,28,0,0,37,45,30,28,0,0,False,False
536,5037,2023-12-13 00:01:47,3,1,141,107,38,45,30,28,0,0,38,45,30,28,0,0,False,False
537,5037,2023-12-13 00:04:27,3,2,160,127,43,51,34,32,0,0,43,51,34,32,0,0,False,True
538,5037,2023-12-13 00:06:48,3,1,140,128,37,45,30,28,0,0,37,45,30,28,0,0,False,False
539,5037,2023-12-13 00:09:06,3,1,139,127,37,45,29,28,0,0,37,45,29,28,0,0,False,False
540,5037,2023-12-13 00:11:27,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
820,5037,2023-12-13 11:57:03,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
821,5037,2023-12-13 11:59:43,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
822,5037,2023-12-13 12:03:12,3,1,123,33,0,63,32,28,0,0,0,63,32,28,0,0,False,False
823,5037,2023-12-13 12:05:11,0,0,118,151,37,33,20,28,0,0,37,33,20,28,0,0,False,True
824,5037,2023-12-13 12:07:43,3,2,152,143,37,59,28,28,0,0,37,59,28,28,0,0,False,True
825,5037,2023-12-13 12:10:23,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
826,5037,2023-12-13 12:13:03,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
827,5037,2023-12-13 12:15:43,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1056,5037,2023-12-13 23:57:07,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1057,5037,2023-12-13 23:59:27,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1058,5037,2023-12-14 00:01:47,3,1,140,107,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1059,5037,2023-12-14 00:04:27,3,2,160,127,43,51,34,32,0,0,43,51,34,32,0,0,False,True
1060,5037,2023-12-14 00:06:47,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1061,5037,2023-12-14 00:09:07,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1062,5037,2023-12-14 00:11:27,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1345,5037,2023-12-14 12:05:03,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
1346,5037,2023-12-14 12:07:43,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
1347,5037,2023-12-14 12:12:20,3,1,28,100,0,0,0,28,0,0,0,0,0,28,0,0,False,False
1348,5037,2023-12-14 12:14:18,0,0,118,58,37,33,20,28,0,0,37,33,20,28,0,0,False,True
1349,5037,2023-12-14 12:17:51,3,2,213,111,49,84,43,37,0,0,49,84,43,37,0,0,False,True
1350,5037,2023-12-14 12:21:03,3,2,192,143,44,76,38,34,0,0,44,76,38,34,0,0,False,True
1351,5037,2023-12-14 12:23:43,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
1352,5037,2023-12-14 12:26:23,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
1353,5037,2023-12-14 12:29:03,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1607,5037,2023-12-14 23:57:06,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1608,5037,2023-12-14 23:59:27,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1609,5037,2023-12-15 00:01:47,3,1,140,107,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1610,5037,2023-12-15 00:04:27,3,2,160,127,43,51,34,32,0,0,43,51,34,32,0,0,False,True
1611,5037,2023-12-15 00:06:47,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1612,5037,2023-12-15 00:09:07,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False
1613,5037,2023-12-15 00:11:27,3,1,140,127,37,45,30,28,0,0,37,45,30,28,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1900,5037,2023-12-15 12:15:43,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
1901,5037,2023-12-15 12:18:23,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
1902,5037,2023-12-15 12:21:22,3,1,123,2,0,63,32,28,0,0,0,63,32,28,0,0,False,False
1903,5037,2023-12-15 12:23:43,0,0,141,143,37,52,24,28,0,0,37,52,24,28,0,0,False,True
1904,5037,2023-12-15 12:26:23,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
1905,5037,2023-12-15 12:29:03,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False
1906,5037,2023-12-15 12:31:43,3,1,160,143,37,63,32,28,0,0,37,63,32,28,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
0,5038,2023-12-12 00:02:18,3,1,140,139,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1,5038,2023-12-12 00:04:59,3,2,160,19,30,74,33,23,0,0,30,74,33,23,0,0,False,True
2,5038,2023-12-12 00:07:19,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
3,5038,2023-12-12 00:09:39,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
4,5038,2023-12-12 00:11:59,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
376,5038,2023-12-12 16:45:30,3,1,160,10,26,74,40,20,0,0,26,74,40,20,0,0,False,False
377,5038,2023-12-12 16:48:09,3,1,159,8,26,74,39,20,0,0,26,74,39,20,0,0,False,False
378,5038,2023-12-12 16:55:11,3,1,166,110,27,74,45,20,0,0,27,74,45,20,0,0,False,False
379,5038,2023-12-12 16:58:44,3,2,213,3,41,105,35,32,0,0,41,105,35,32,0,0,False,True
380,5038,2023-12-12 17:01:30,3,2,166,89,27,77,42,20,0,0,27,77,42,20,0,0,True,True
381,5038,2023-12-12 17:04:01,3,2,151,60,26,71,34,20,0,0,26,71,34,20,0,0,True,True
382,5038,2023-12-12 17:06:35,3,2,154,34,26,73,35,20,0,0,26,73,35,20,0,0,True,True
383,5038,2023-12-12 17:09:35,3,1,180,34,26,89,45,20,0,0,26,89,45,20,0,0,True,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
532,5038,2023-12-12 23:57:38,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
533,5038,2023-12-12 23:59:59,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
534,5038,2023-12-13 00:02:19,3,1,140,139,26,65,29,20,0,0,26,65,29,20,0,0,False,False
535,5038,2023-12-13 00:04:59,3,2,160,19,30,74,33,23,0,0,30,74,33,23,0,0,False,True
536,5038,2023-12-13 00:07:19,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
537,5038,2023-12-13 00:09:39,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
538,5038,2023-12-13 00:11:59,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
588,5038,2023-12-13 02:08:39,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
589,5038,2023-12-13 02:10:59,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
590,5038,2023-12-13 02:13:19,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
591,5038,2023-12-13 02:15:58,3,1,160,38,26,85,29,20,0,0,26,85,29,20,0,0,False,True
592,5038,2023-12-13 02:18:00,3,2,121,20,27,43,30,21,0,0,27,43,30,21,0,0,False,True
593,5038,2023-12-13 02:20:19,3,1,139,19,26,64,29,20,0,0,26,64,29,20,0,0,False,False
594,5038,2023-12-13 02:22:39,3,1,140,18,26,65,29,20,0,0,26,65,29,20,0,0,False,False
595,5038,2023-12-13 02:24:59,3,1,141,20,27,65,29,20,0,0,27,65,29,20,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1054,5038,2023-12-13 23:57:39,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1055,5038,2023-12-13 23:59:59,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1056,5038,2023-12-14 00:02:19,3,1,140,139,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1057,5038,2023-12-14 00:04:59,3,2,160,19,30,74,33,23,0,0,30,74,33,23,0,0,False,True
1058,5038,2023-12-14 00:07:19,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1059,5038,2023-12-14 00:09:39,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1060,5038,2023-12-14 00:11:59,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1607,5038,2023-12-14 23:57:40,3,1,141,20,27,65,29,20,0,0,27,65,29,20,0,0,False,False
1608,5038,2023-12-14 23:59:59,3,1,139,19,26,64,29,20,0,0,26,64,29,20,0,0,False,False
1609,5038,2023-12-15 00:02:19,3,1,140,139,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1610,5038,2023-12-15 00:04:59,3,2,160,19,30,74,33,23,0,0,30,74,33,23,0,0,False,True
1611,5038,2023-12-15 00:07:19,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1612,5038,2023-12-15 00:09:39,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1613,5038,2023-12-15 00:11:59,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1663,5038,2023-12-15 02:08:39,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1664,5038,2023-12-15 02:10:59,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1665,5038,2023-12-15 02:13:19,3,1,140,19,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1666,5038,2023-12-15 02:16:25,3,1,186,64,26,111,29,20,0,0,26,111,29,20,0,0,False,True
1667,5038,2023-12-15 02:18:45,3,2,140,64,26,52,42,20,0,0,26,52,42,20,0,0,False,True
1668,5038,2023-12-15 02:20:43,3,2,118,42,26,43,29,20,0,0,26,43,29,20,0,0,False,True
1669,5038,2023-12-15 02:22:41,3,2,118,21,26,43,29,20,0,0,26,43,29,20,0,0,False,True
1670,5038,2023-12-15 02:24:59,3,1,138,19,26,63,29,20,0,0,26,63,29,20,0,0,False,True
1671,5038,2023-12-15 02:27:19,3,1,140,18,26,65,29,20,0,0,26,65,29,20,0,0,False,False
1672,5038,2023-12-15 02:29:40,3,1,141,20,27,65,29,20,0,0,27,65,29,20,0,0,False,False
1673,5038,2023-12-15 02:31:59,3,1,139,19,26,64,29,20,0,0,26,64,29,20,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
383,5039,2023-12-12 18:10:46,3,1,181,106,45,136,0,0,0,0,45,136,0,0,0,0,False,False
384,5039,2023-12-12 18:13:44,3,1,179,105,45,134,0,0,0,0,45,134,0,0,0,0,False,False
385,5039,2023-12-12 18:16:45,3,1,180,106,45,135,0,0,0,0,45,135,0,0,0,0,False,False
386,5039,2023-12-12 18:20:53,3,1,248,174,45,203,0,0,0,0,45,203,0,0,0,0,False,True
387,5039,2023-12-12 18:24:52,3,2,239,53,45,194,0,0,0,0,45,194,0,0,0,0,False,True
388,5039,2023-12-12 18:28:45,3,2,232,105,45,187,0,0,0,0,45,187,0,0,0,0,False,True
389,5039,2023-12-12 18:31:44,3,1,180,105,45,135,0,0,0,0,45,135,0,0,0,0,False,False
390,5039,2023-12-12 18:34:44,3,1,180,104,45,135,0,0,0,0,45,135,0,0,0,0,False,False
391,5039,2023-12-12 18:37:46,3,1,181,106,45,136,0,0,0,0,45,136,0,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1498,5039,2023-12-14 23:00:00,3,1,160,80,45,115,0,0,0,0,45,115,0,0,0,0,False,False
1499,5039,2023-12-14 23:02:39,3,1,160,79,45,115,0,0,0,0,45,115,0,0,0,0,False,False
1500,5039,2023-12-14 23:05:21,3,1,161,82,45,116,0,0,0,0,45,116,0,0,0,0,False,False
1501,5039,2023-12-14 23:07:59,3,1,158,79,45,113,0,0,0,0,45,113,0,0,0,0,False,True
1502,5039,2023-12-14 23:10:40,3,1,161,80,45,116,0,0,0,0,45,116,0,0,0,0,False,False
1503,5039,2023-12-14 23:13:20,3,1,160,80,45,115,0,0,0,0,45,115,0,0,0,0,False,False
1504,5039,2023-12-14 23:16:00,3,1,160,80,45,115,0,0,0,0,45,115,0,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1518,5039,2023-12-14 23:53:40,3,1,149,69,45,104,0,0,0,0,45,104,0,0,0,0,False,False
1519,5039,2023-12-14 23:56:11,3,1,151,70,45,106,0,0,0,0,45,106,0,0,0,0,False,False
1520,5039,2023-12-14 23:58:41,3,1,150,70,45,105,0,0,0,0,45,105,0,0,0,0,False,False
1521,5039,2023-12-14 23:59:46,3,1,131,67,33,34,30,34,0,0,33,34,30,34,0,0,False,True
1522,5039,2023-12-15 00:01:11,3,1,150,70,45,105,0,0,0,0,45,105,0,0,0,0,False,False
1523,5039,2023-12-15 00:03:41,3,1,150,70,45,105,0,0,0,0,45,105,0,0,0,0,False,False
1524,5039,2023-12-15 00:06:11,3,1,150,70,45,105,0,0,0,0,45,105,0,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1643,5039,2023-12-15 05:03:39,3,1,150,69,45,105,0,0,0,0,45,105,0,0,0,0,False,False
1644,5039,2023-12-15 05:06:10,3,1,151,70,45,106,0,0,0,0,45,106,0,0,0,0,False,False
1645,5039,2023-12-15 05:08:41,3,1,150,72,45,105,0,0,0,0,45,105,0,0,0,0,False,False
1646,5039,2023-12-15 05:11:09,3,1,148,69,45,103,0,0,0,0,45,103,0,0,0,0,False,True
1647,5039,2023-12-15 05:13:40,3,1,151,70,45,106,0,0,0,0,45,106,0,0,0,0,False,False
1648,5039,2023-12-15 05:16:10,3,1,150,70,45,105,0,0,0,0,45,105,0,0,0,0,False,False
1649,5039,2023-12-15 05:18:40,3,1,150,70,45,105,0,0,0,0,45,105,0,0,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
11,5040,2023-12-12 00:28:55,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False
12,5040,2023-12-12 00:31:25,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False
13,5040,2023-12-12 00:33:55,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False
14,5040,2023-12-12 00:37:14,3,1,199,133,41,99,19,40,0,0,41,99,19,40,0,0,False,True
15,5040,2023-12-12 00:40:34,3,2,200,33,60,52,30,58,0,0,60,52,30,58,0,0,False,True
16,5040,2023-12-12 00:43:54,3,2,200,83,55,67,25,53,0,0,55,67,25,53,0,0,False,True
17,5040,2023-12-12 00:46:25,3,1,151,84,42,50,19,40,0,0,42,50,19,40,0,0,False,False
18,5040,2023-12-12 00:48:55,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False
19,5040,2023-12-12 00:51:25,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
382,5040,2023-12-12 18:10:58,3,1,180,119,41,77,22,40,0,0,41,77,22,40,0,0,False,False
383,5040,2023-12-12 18:13:58,3,1,180,119,41,77,22,40,0,0,41,77,22,40,0,0,False,False
384,5040,2023-12-12 18:16:58,3,1,180,119,41,77,22,40,0,0,41,77,22,40,0,0,False,False
385,5040,2023-12-12 18:21:09,3,1,251,10,41,148,22,40,0,0,41,148,22,40,0,0,False,True
386,5040,2023-12-12 18:25:08,3,2,239,68,69,60,43,67,0,0,69,60,43,67,0,0,False,True
387,5040,2023-12-12 18:28:59,3,2,231,119,53,99,28,51,0,0,53,99,28,51,0,0,False,True
388,5040,2023-12-12 18:31:59,3,1,180,119,41,77,22,40,0,0,41,77,22,40,0,0,False,False
389,5040,2023-12-12 18:34:59,3,1,180,120,41,77,22,40,0,0,41,77,22,40,0,0,False,False
390,5040,2023-12-12 18:37:58,3,1,179,119,41,77,21,40,0,0,41,77,21,40,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1517,5040,2023-12-14 23:53:55,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False
1518,5040,2023-12-14 23:56:24,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False
1519,5040,2023-12-14 23:58:54,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False
1520,5040,2023-12-14 23:59:46,3,1,131,67,33,34,30,34,0,0,33,34,30,34,0,0,False,True
1521,5040,2023-12-15 00:01:25,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False
1522,5040,2023-12-15 00:03:55,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False
1523,5040,2023-12-15 00:06:25,3,1,150,84,41,50,19,40,0,0,41,50,19,40,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
10,5041,2023-12-12 00:26:19,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False
11,5041,2023-12-12 00:28:48,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False
12,5041,2023-12-12 00:31:19,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False
13,5041,2023-12-12 00:33:53,3,1,153,83,46,87,10,10,0,0,46,87,10,10,0,0,False,True
14,5041,2023-12-12 00:36:19,0,0,146,79,46,80,10,10,0,0,46,80,10,10,0,0,False,True
15,5041,2023-12-12 00:38:41,0,0,142,71,46,65,21,10,0,0,46,65,21,10,0,0,False,True
16,5041,2023-12-12 00:41:16,3,2,155,76,46,88,11,10,0,0,46,88,11,10,0,0,False,True
17,5041,2023-12-12 00:43:47,3,1,152,78,46,86,10,10,0,0,46,86,10,10,0,0,False,True
18,5041,2023-12-12 00:46:19,3,1,151,79,46,85,10,10,0,0,46,85,10,10,0,0,False,False
19,5041,2023-12-12 00:48:49,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False
20,5041,2023-12-12 00:51:18,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
383,5041,2023-12-12 18:10:54,3,1,180,114,46,113,11,10,0,0,46,113,11,10,0,0,False,False
384,5041,2023-12-12 18:13:53,3,1,180,114,46,113,11,10,0,0,46,113,11,10,0,0,False,False
385,5041,2023-12-12 18:16:54,3,1,180,114,46,113,11,10,0,0,46,113,11,10,0,0,False,False
386,5041,2023-12-12 18:20:07,3,1,193,127,46,126,11,10,0,0,46,126,11,10,0,0,False,True
387,5041,2023-12-12 18:22:46,0,0,159,106,46,78,25,10,0,0,46,78,25,10,0,0,False,True
388,5041,2023-12-12 18:25:51,3,2,185,111,46,118,11,10,0,0,46,118,11,10,0,0,False,True
389,5041,2023-12-12 18:28:53,3,1,182,114,46,115,11,10,0,0,46,115,11,10,0,0,False,True
390,5041,2023-12-12 18:31:53,3,1,180,113,46,113,11,10,0,0,46,113,11,10,0,0,False,False
391,5041,2023-12-12 18:34:54,3,1,181,115,46,114,11,10,0,0,46,114,11,10,0,0,False,False
392,5041,2023-12-12 18:37:53,3,1,179,113,46,112,11,10,0,0,46,112,11,10,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1520,5041,2023-12-14 23:53:49,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False
1521,5041,2023-12-14 23:56:19,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False
1522,5041,2023-12-14 23:58:49,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False
1523,5041,2023-12-14 23:59:46,3,1,131,67,33,34,30,34,0,0,33,34,30,34,0,0,False,True
1524,5041,2023-12-15 00:01:20,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False
1525,5041,2023-12-15 00:03:49,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False
1526,5041,2023-12-15 00:06:19,3,1,150,79,46,84,10,10,0,0,46,84,10,10,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
382,5042,2023-12-12 18:10:49,0,0,180,110,36,72,29,22,13,8,36,72,29,22,13,8,False,False
383,5042,2023-12-12 18:13:49,0,0,180,110,36,72,29,22,13,8,36,72,29,22,13,8,False,False
384,5042,2023-12-12 18:16:49,0,0,180,110,36,72,29,22,13,8,36,72,29,22,13,8,False,False
385,5042,2023-12-12 18:20:45,0,0,236,165,92,72,29,22,13,8,92,72,29,22,13,8,False,True
386,5042,2023-12-12 18:23:15,0,0,150,135,33,50,29,17,13,8,33,50,29,17,13,8,False,False
387,5042,2023-12-12 18:25:49,0,0,154,109,33,53,29,18,13,8,33,53,29,18,13,8,False,True
388,5042,2023-12-12 18:28:49,0,0,180,109,36,72,29,22,13,8,36,72,29,22,13,8,False,False
389,5042,2023-12-12 18:31:49,0,0,180,109,36,72,29,22,13,8,36,72,29,22,13,8,False,False
390,5042,2023-12-12 18:34:49,0,0,180,109,36,72,29,22,13,8,36,72,29,22,13,8,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
800,5042,2023-12-13 13:12:11,0,0,170,101,35,65,29,20,13,8,35,65,29,20,13,8,False,False
801,5042,2023-12-13 13:15:01,0,0,170,101,35,65,29,20,13,8,35,65,29,20,13,8,False,False
802,5042,2023-12-13 13:17:51,0,0,170,101,35,65,29,20,13,8,35,65,29,20,13,8,False,False
803,5042,2023-12-13 13:20:48,0,0,178,108,43,65,29,20,13,8,43,65,29,20,13,8,False,True
804,5042,2023-12-13 13:23:31,0,0,163,101,33,61,29,19,13,8,33,61,29,19,13,8,False,True
805,5042,2023-12-13 13:26:22,0,0,170,101,35,65,29,20,13,8,35,65,29,20,13,8,False,False
806,5042,2023-12-13 13:29:11,0,0,170,101,35,65,29,20,13,8,35,65,29,20,13,8,False,False
807,5042,2023-12-13 13:32:02,0,0,170,101,35,65,29,20,13,8,35,65,29,20,13,8,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
802,5043,2023-12-13 13:14:49,3,1,170,89,41,70,8,11,40,0,41,70,8,11,40,0,False,False
803,5043,2023-12-13 13:17:39,3,1,170,89,41,70,8,11,40,0,41,70,8,11,40,0,False,False
804,5043,2023-12-13 13:20:29,0,0,170,89,41,70,8,11,40,0,41,70,8,11,40,0,False,False
805,5043,2023-12-13 13:23:19,0,0,170,89,47,52,14,11,46,0,47,52,14,11,46,0,False,True
806,5043,2023-12-13 13:26:09,3,1,170,89,41,70,8,11,40,0,41,70,8,11,40,0,False,False
807,5043,2023-12-13 13:28:59,3,1,170,89,41,70,8,11,40,0,41,70,8,11,40,0,False,False
808,5043,2023-12-13 13:31:49,3,1,170,89,41,70,8,11,40,0,41,70,8,11,40,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1519,5043,2023-12-14 23:53:41,3,1,150,71,39,52,8,11,40,0,39,52,8,11,40,0,False,False
1520,5043,2023-12-14 23:56:11,3,1,150,71,39,52,8,11,40,0,39,52,8,11,40,0,False,False
1521,5043,2023-12-14 23:58:41,3,1,150,71,39,52,8,11,40,0,39,52,8,11,40,0,False,False
1522,5043,2023-12-14 23:59:46,3,1,131,67,33,34,30,34,0,0,33,34,30,34,0,0,False,True
1523,5043,2023-12-15 00:01:11,3,1,150,71,39,52,8,11,40,0,39,52,8,11,40,0,False,False
1524,5043,2023-12-15 00:03:41,3,1,150,71,39,52,8,11,40,0,39,52,8,11,40,0,False,False
1525,5043,2023-12-15 00:06:11,3,1,150,71,39,52,8,11,40,0,39,52,8,11,40,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
802,5044,2023-12-13 13:15:10,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False
803,5044,2023-12-13 13:18:00,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False
804,5044,2023-12-13 13:20:51,0,0,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False
805,5044,2023-12-13 13:23:38,0,0,167,107,43,47,20,22,19,16,43,47,20,22,19,16,False,True
806,5044,2023-12-13 13:26:30,3,1,173,110,42,63,17,19,16,16,42,63,17,19,16,16,False,True
807,5044,2023-12-13 13:29:21,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False
808,5044,2023-12-13 13:32:11,3,1,170,111,40,62,17,19,16,16,40,62,17,19,16,16,False,False
809,5044,2023-12-13 13:34:59,3,1,169,109,40,62,17,19,15,16,40,62,17,19,15,16,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1343,5044,2023-12-14 15:36:50,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False
1344,5044,2023-12-14 15:39:40,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False
1345,5044,2023-12-14 15:42:30,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False
1346,5044,2023-12-14 15:46:23,0,0,232,2,102,62,17,19,16,16,102,62,17,19,16,16,False,True
1347,5044,2023-12-14 15:48:42,0,0,139,141,40,41,15,15,12,16,40,41,15,15,12,16,False,False
1348,5044,2023-12-14 15:51:05,3,2,143,114,40,45,15,15,12,16,40,45,15,15,12,16,False,True
1349,5044,2023-12-14 15:53:51,3,2,166,110,40,61,16,18,15,16,40,61,16,18,15,16,False,False
1350,5044,2023-12-14 15:56:41,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False
1351,5044,2023-12-14 15:59:31,3,1,170,110,40,62,17,19,16,16,40,62,17,19,16,16,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1517,5044,2023-12-14 23:54:00,3,1,150,90,40,50,15,17,12,16,40,50,15,17,12,16,False,False
1518,5044,2023-12-14 23:56:30,3,1,150,90,40,50,15,17,12,16,40,50,15,17,12,16,False,False
1519,5044,2023-12-14 23:59:00,3,1,150,90,40,50,15,17,12,16,40,50,15,17,12,16,False,False
1520,5044,2023-12-14 23:59:46,3,1,131,67,33,34,30,34,0,0,33,34,30,34,0,0,False,True
1521,5044,2023-12-15 00:01:30,3,1,150,90,40,50,15,17,12,16,40,50,15,17,12,16,False,False
1522,5044,2023-12-15 00:04:00,3,1,150,90,40,50,15,17,12,16,40,50,15,17,12,16,False,False
1523,5044,2023-12-15 00:06:30,3,1,150,90,40,50,15,17,12,16,40,50,15,17,12,16,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
154,5045,2023-12-12 06:50:43,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
155,5045,2023-12-12 06:54:23,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
156,5045,2023-12-12 06:58:03,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
157,5045,2023-12-12 07:02:17,0,0,254,37,46,124,41,43,0,0,30,140,41,43,0,0,False,True
158,5045,2023-12-12 07:06:01,0,0,224,41,40,110,36,38,0,0,27,123,36,38,0,0,False,True
159,5045,2023-12-12 07:09:41,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
160,5045,2023-12-12 07:13:21,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
161,5045,2023-12-12 07:17:01,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
174,5045,2023-12-12 08:04:41,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
175,5045,2023-12-12 08:08:21,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
176,5045,2023-12-12 08:12:01,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
177,5045,2023-12-12 09:02:43,0,0,182,3,21,89,36,36,0,0,19,91,36,36,0,0,False,True
178,5045,2023-12-12 09:06:23,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False
179,5045,2023-12-12 09:10:03,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False
180,5045,2023-12-12 09:13:43,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
243,5045,2023-12-12 12:26:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
244,5045,2023-12-12 12:29:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
245,5045,2023-12-12 12:34:28,0,0,180,88,27,81,36,36,0,0,27,81,36,36,0,0,False,False
246,5045,2023-12-12 12:38:27,0,0,239,147,35,108,48,48,0,0,35,108,48,48,0,0,False,True
247,5045,2023-12-12 12:41:54,0,0,207,174,32,93,41,41,0,0,32,93,41,41,0,0,False,True
248,5045,2023-12-12 12:44:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
249,5045,2023-12-12 12:47:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
250,5045,2023-12-12 12:50:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
627,5045,2023-12-13 06:50:43,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
628,5045,2023-12-13 06:54:23,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
629,5045,2023-12-13 06:58:03,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
630,5045,2023-12-13 07:02:17,0,0,254,37,46,124,41,43,0,0,30,140,41,43,0,0,False,True
631,5045,2023-12-13 07:06:01,0,0,224,42,40,110,36,38,0,0,27,123,36,38,0,0,False,True
632,5045,2023-12-13 07:09:41,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
633,5045,2023-12-13 07:13:21,0,0,220,42,38,108,36,38,0,0,25,121,36,38,0,0,False,False
634,5045,2023-12-13 07:17:01,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
660,5045,2023-12-13 08:52:21,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
661,5045,2023-12-13 08:56:01,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
662,5045,2023-12-13 08:59:41,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
663,5045,2023-12-13 09:02:43,0,0,182,3,21,89,36,36,0,0,19,91,36,36,0,0,False,True
664,5045,2023-12-13 09:06:23,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False
665,5045,2023-12-13 09:10:03,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False
666,5045,2023-12-13 09:13:43,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1087,5045,2023-12-14 06:50:43,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1088,5045,2023-12-14 06:54:23,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1089,5045,2023-12-14 06:58:03,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1090,5045,2023-12-14 07:02:17,0,0,254,37,46,124,41,43,0,0,30,140,41,43,0,0,False,True
1091,5045,2023-12-14 07:06:01,0,0,224,41,40,110,36,38,0,0,27,123,36,38,0,0,False,True
1092,5045,2023-12-14 07:09:41,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1093,5045,2023-12-14 07:13:21,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1094,5045,2023-12-14 07:17:01,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1120,5045,2023-12-14 08:52:21,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1121,5045,2023-12-14 08:56:01,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1122,5045,2023-12-14 08:59:41,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1123,5045,2023-12-14 09:02:43,0,0,182,3,21,89,36,36,0,0,19,91,36,36,0,0,False,True
1124,5045,2023-12-14 09:06:23,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1125,5045,2023-12-14 09:10:03,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1126,5045,2023-12-14 09:13:43,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1150,5045,2023-12-14 10:29:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
1151,5045,2023-12-14 10:32:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
1152,5045,2023-12-14 10:36:13,0,0,180,13,27,81,36,36,0,0,27,81,36,36,0,0,False,False
1153,5045,2023-12-14 10:38:56,0,0,163,176,19,72,36,36,0,0,19,72,36,36,0,0,False,True
1154,5045,2023-12-14 10:41:54,0,0,178,174,26,80,36,36,0,0,26,80,36,36,0,0,False,False
1155,5045,2023-12-14 10:44:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
1156,5045,2023-12-14 10:47:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1395,5045,2023-12-14 22:53:30,0,0,160,10,22,66,36,36,0,0,22,66,36,36,0,0,False,False
1396,5045,2023-12-14 22:56:10,0,0,160,10,22,66,36,36,0,0,22,66,36,36,0,0,False,False
1397,5045,2023-12-14 23:00:03,0,0,160,83,22,66,36,36,0,0,22,66,36,36,0,0,False,False
1398,5045,2023-12-14 23:03:35,0,0,212,135,31,87,47,47,0,0,31,87,47,47,0,0,False,True
1399,5045,2023-12-14 23:06:49,0,0,195,10,29,80,43,43,0,0,29,80,43,43,0,0,False,True
1400,5045,2023-12-14 23:09:30,0,0,160,10,22,66,36,36,0,0,22,66,36,36,0,0,False,False
1401,5045,2023-12-14 23:12:10,0,0,160,10,22,66,36,36,0,0,22,66,36,36,0,0,False,False
1402,5045,2023-12-14 23:14:50,0,0,160,10,22,66,36,36,0,0,22,66,36,36,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1416,5045,2023-12-14 23:52:47,0,0,150,17,20,58,36,36,0,0,20,58,36,36,0,0,False,False
1417,5045,2023-12-14 23:55:17,0,0,150,17,20,58,36,36,0,0,20,58,36,36,0,0,False,False
1418,5045,2023-12-14 23:57:47,0,0,150,17,20,58,36,36,0,0,20,58,36,36,0,0,False,False
1419,5045,2023-12-14 23:59:46,3,1,131,67,33,34,30,34,0,0,33,34,30,34,0,0,False,True
1420,5045,2023-12-15 00:00:16,0,0,150,16,20,58,36,36,0,0,20,58,36,36,0,0,False,False
1421,5045,2023-12-15 00:02:46,0,0,150,16,20,58,36,36,0,0,20,58,36,36,0,0,False,False
1422,5045,2023-12-15 00:05:16,0,0,150,16,20,58,36,36,0,0,20,58,36,36,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1574,5045,2023-12-15 06:50:43,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1575,5045,2023-12-15 06:54:23,0,0,220,3,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1576,5045,2023-12-15 06:58:03,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1577,5045,2023-12-15 07:02:17,0,0,254,37,46,124,41,43,0,0,30,140,41,43,0,0,False,True
1578,5045,2023-12-15 07:06:01,0,0,224,42,40,110,36,38,0,0,27,123,36,38,0,0,False,True
1579,5045,2023-12-15 07:09:41,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1580,5045,2023-12-15 07:13:21,0,0,220,42,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1581,5045,2023-12-15 07:17:01,0,0,220,42,38,108,36,38,0,0,25,121,36,38,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1607,5045,2023-12-15 08:52:21,0,0,220,42,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1608,5045,2023-12-15 08:56:01,0,0,220,42,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1609,5045,2023-12-15 08:59:41,0,0,220,41,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1610,5045,2023-12-15 09:02:43,0,0,182,4,21,89,36,36,0,0,19,91,36,36,0,0,False,True
1611,5045,2023-12-15 09:06:23,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1612,5045,2023-12-15 09:10:03,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False
1613,5045,2023-12-15 09:13:43,0,0,220,4,38,108,36,38,0,0,25,121,36,38,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1765,5045,2023-12-15 16:53:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
1766,5045,2023-12-15 16:56:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
1767,5045,2023-12-15 16:59:54,0,0,180,174,27,81,36,36,0,0,27,81,36,36,0,0,False,False
1768,5045,2023-12-15 23:59:30,3,1,130,51,36,14,27,27,26,0,36,14,27,27,26,0,False,True

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
3,5046,2023-12-12 00:07:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
4,5046,2023-12-12 00:10:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
5,5046,2023-12-12 00:12:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
6,5046,2023-12-12 00:15:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
7,5046,2023-12-12 00:17:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
8,5046,2023-12-12 00:20:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
9,5046,2023-12-12 00:22:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
13,5046,2023-12-12 00:32:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
14,5046,2023-12-12 00:35:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
15,5046,2023-12-12 00:37:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
16,5046,2023-12-12 00:40:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
17,5046,2023-12-12 00:42:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
18,5046,2023-12-12 00:45:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
19,5046,2023-12-12 00:47:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
23,5046,2023-12-12 00:57:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
24,5046,2023-12-12 01:00:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
25,5046,2023-12-12 01:02:40,0,0,151,10,24,42,43,42,0,0,24,42,43,42,0,0,False,False
26,5046,2023-12-12 01:05:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
27,5046,2023-12-12 01:07:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
28,5046,2023-12-12 01:10:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
29,5046,2023-12-12 01:12:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
33,5046,2023-12-12 01:22:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
34,5046,2023-12-12 01:25:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
35,5046,2023-12-12 01:27:40,0,0,151,10,24,42,43,42,0,0,24,42,43,42,0,0,False,False
36,5046,2023-12-12 01:30:09,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
37,5046,2023-12-12 01:32:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
38,5046,2023-12-12 01:35:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
39,5046,2023-12-12 01:37:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
43,5046,2023-12-12 01:47:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
44,5046,2023-12-12 01:50:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
45,5046,2023-12-12 01:52:40,0,0,151,10,24,42,43,42,0,0,24,42,43,42,0,0,False,False
46,5046,2023-12-12 01:55:09,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
47,5046,2023-12-12 01:57:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
48,5046,2023-12-12 02:00:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
49,5046,2023-12-12 02:02:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
53,5046,2023-12-12 02:12:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
54,5046,2023-12-12 02:15:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
55,5046,2023-12-12 02:17:40,0,0,151,10,24,42,43,42,0,0,24,42,43,42,0,0,False,False
56,5046,2023-12-12 02:20:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
57,5046,2023-12-12 02:22:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
58,5046,2023-12-12 02:25:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
59,5046,2023-12-12 02:27:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
63,5046,2023-12-12 02:37:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
64,5046,2023-12-12 02:40:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
65,5046,2023-12-12 02:42:40,0,0,151,10,24,42,43,42,0,0,24,42,43,42,0,0,False,False
66,5046,2023-12-12 02:45:09,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
67,5046,2023-12-12 02:47:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
68,5046,2023-12-12 02:50:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
69,5046,2023-12-12 02:52:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
72,5046,2023-12-12 03:00:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
73,5046,2023-12-12 03:02:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
74,5046,2023-12-12 03:05:10,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
75,5046,2023-12-12 03:07:38,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
76,5046,2023-12-12 03:10:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
77,5046,2023-12-12 03:12:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
78,5046,2023-12-12 03:15:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
82,5046,2023-12-12 03:25:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
83,5046,2023-12-12 03:27:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
84,5046,2023-12-12 03:30:10,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
85,5046,2023-12-12 03:32:39,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
86,5046,2023-12-12 03:35:09,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
87,5046,2023-12-12 03:37:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
88,5046,2023-12-12 03:40:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
92,5046,2023-12-12 03:50:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
93,5046,2023-12-12 03:52:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
94,5046,2023-12-12 03:55:10,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
95,5046,2023-12-12 03:57:39,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
96,5046,2023-12-12 04:00:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
97,5046,2023-12-12 04:02:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
98,5046,2023-12-12 04:05:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
102,5046,2023-12-12 04:15:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
103,5046,2023-12-12 04:17:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
104,5046,2023-12-12 04:20:10,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
105,5046,2023-12-12 04:22:38,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
106,5046,2023-12-12 04:25:09,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
107,5046,2023-12-12 04:27:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
108,5046,2023-12-12 04:30:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
112,5046,2023-12-12 04:40:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
113,5046,2023-12-12 04:42:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
114,5046,2023-12-12 04:45:10,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
115,5046,2023-12-12 04:47:39,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
116,5046,2023-12-12 04:50:09,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
117,5046,2023-12-12 04:52:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
118,5046,2023-12-12 04:55:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
150,5046,2023-12-12 06:32:38,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
151,5046,2023-12-12 06:36:18,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
152,5046,2023-12-12 06:39:58,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
153,5046,2023-12-12 06:43:36,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
154,5046,2023-12-12 06:47:17,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
155,5046,2023-12-12 06:50:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
156,5046,2023-12-12 06:54:37,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
160,5046,2023-12-12 07:09:18,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
161,5046,2023-12-12 07:12:58,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
162,5046,2023-12-12 07:16:39,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
163,5046,2023-12-12 07:20:17,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
164,5046,2023-12-12 07:23:57,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
165,5046,2023-12-12 07:27:37,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
166,5046,2023-12-12 07:31:17,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
170,5046,2023-12-12 07:45:58,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
171,5046,2023-12-12 07:49:38,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
172,5046,2023-12-12 07:53:19,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
173,5046,2023-12-12 07:56:57,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
174,5046,2023-12-12 08:00:37,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
175,5046,2023-12-12 08:04:17,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
176,5046,2023-12-12 08:07:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
177,5046,2023-12-12 08:11:37,0,0,221,18,40,96,42,43,0,0,40,96,42,43,0,0,False,False
178,5046,2023-12-12 09:02:58,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
179,5046,2023-12-12 09:06:38,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
180,5046,2023-12-12 09:10:17,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
181,5046,2023-12-12 09:13:57,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
182,5046,2023-12-12 09:17:37,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
183,5046,2023-12-12 09:21:17,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
244,5046,2023-12-12 12:26:42,0,0,180,162,30,66,42,42,0,0,30,66,42,42,0,0,False,False
245,5046,2023-12-12 12:29:42,0,0,181,162,30,66,42,43,0,0,30,66,42,43,0,0,False,False
246,5046,2023-12-12 12:32:42,0,0,180,162,30,66,42,42,0,0,30,66,42,42,0,0,False,False
247,5046,2023-12-12 12:36:09,0,0,207,10,30,93,42,42,0,0,30,93,42,42,0,0,False,True
248,5046,2023-12-12 12:38:42,0,0,153,163,19,49,42,43,0,0,19,49,42,43,0,0,False,True
249,5046,2023-12-12 12:41:43,0,0,180,163,30,66,42,42,0,0,30,66,42,42,0,0,False,False
250,5046,2023-12-12 12:44:43,0,0,180,163,30,66,42,42,0,0,30,66,42,42,0,0,False,False
251,5046,2023-12-12 12:47:43,0,0,181,163,30,66,42,43,0,0,30,66,42,43,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
458,5046,2023-12-12 23:11:49,0,0,160,149,24,52,42,42,0,0,24,52,42,42,0,0,False,False
459,5046,2023-12-12 23:14:29,0,0,160,149,24,52,42,42,0,0,24,52,42,42,0,0,False,False
460,5046,2023-12-12 23:17:09,0,0,161,150,24,52,42,43,0,0,24,52,42,43,0,0,False,False
461,5046,2023-12-12 23:19:47,0,0,158,148,22,51,42,43,0,0,22,51,42,43,0,0,False,True
462,5046,2023-12-12 23:22:28,0,0,160,148,24,52,42,42,0,0,24,52,42,42,0,0,False,False
463,5046,2023-12-12 23:25:08,0,0,160,148,24,52,42,42,0,0,24,52,42,42,0,0,False,False
464,5046,2023-12-12 23:27:48,0,0,160,148,24,52,42,42,0,0,24,52,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
474,5046,2023-12-12 23:52:39,0,0,151,9,24,42,42,43,0,0,24,42,42,43,0,0,False,False
475,5046,2023-12-12 23:55:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
476,5046,2023-12-12 23:57:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
477,5046,2023-12-12 23:59:55,3,1,100,95,20,80,0,0,0,0,20,80,0,0,0,0,False,True
478,5046,2023-12-13 00:00:10,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
479,5046,2023-12-13 00:02:39,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
480,5046,2023-12-13 00:05:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
481,5046,2023-12-13 00:07:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
482,5046,2023-12-13 00:10:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
483,5046,2023-12-13 00:12:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
484,5046,2023-12-13 00:15:08,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
485,5046,2023-12-13 00:17:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
486,5046,2023-12-13 00:20:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
487,5046,2023-12-13 00:22:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
491,5046,2023-12-13 00:32:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
492,5046,2023-12-13 00:35:11,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
493,5046,2023-12-13 00:37:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
494,5046,2023-12-13 00:40:08,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
495,5046,2023-12-13 00:42:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
496,5046,2023-12-13 00:45:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
497,5046,2023-12-13 00:47:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
501,5046,2023-12-13 00:57:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
502,5046,2023-12-13 01:00:11,0,0,150,11,24,42,42,42,0,0,24,42,42,42,0,0,False,False
503,5046,2023-12-13 01:02:41,0,0,151,11,25,42,42,42,0,0,25,42,42,42,0,0,False,False
504,5046,2023-12-13 01:05:09,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
505,5046,2023-12-13 01:07:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
506,5046,2023-12-13 01:10:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
507,5046,2023-12-13 01:12:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
510,5046,2023-12-13 01:20:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
511,5046,2023-12-13 01:22:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
512,5046,2023-12-13 01:25:11,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
513,5046,2023-12-13 01:27:39,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
514,5046,2023-12-13 01:30:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
515,5046,2023-12-13 01:32:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
516,5046,2023-12-13 01:35:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
520,5046,2023-12-13 01:45:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
521,5046,2023-12-13 01:47:41,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
522,5046,2023-12-13 01:50:10,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
523,5046,2023-12-13 01:52:39,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
524,5046,2023-12-13 01:55:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
525,5046,2023-12-13 01:57:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
526,5046,2023-12-13 02:00:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
530,5046,2023-12-13 02:10:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
531,5046,2023-12-13 02:12:41,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
532,5046,2023-12-13 02:15:11,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
533,5046,2023-12-13 02:17:39,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
534,5046,2023-12-13 02:20:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
535,5046,2023-12-13 02:22:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
536,5046,2023-12-13 02:25:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
540,5046,2023-12-13 02:35:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
541,5046,2023-12-13 02:37:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
542,5046,2023-12-13 02:40:11,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
543,5046,2023-12-13 02:42:39,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
544,5046,2023-12-13 02:45:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
545,5046,2023-12-13 02:47:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
546,5046,2023-12-13 02:50:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
550,5046,2023-12-13 03:00:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
551,5046,2023-12-13 03:02:41,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
552,5046,2023-12-13 03:05:11,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
553,5046,2023-12-13 03:07:39,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
554,5046,2023-12-13 03:10:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
555,5046,2023-12-13 03:12:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
556,5046,2023-12-13 03:15:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
560,5046,2023-12-13 03:25:11,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
561,5046,2023-12-13 03:27:41,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
562,5046,2023-12-13 03:30:11,0,0,151,11,24,42,43,42,0,0,24,42,43,42,0,0,False,False
563,5046,2023-12-13 03:32:39,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
564,5046,2023-12-13 03:35:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
565,5046,2023-12-13 03:37:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
566,5046,2023-12-13 03:40:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
570,5046,2023-12-13 03:50:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
571,5046,2023-12-13 03:52:41,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
572,5046,2023-12-13 03:55:11,0,0,151,11,24,42,43,42,0,0,24,42,43,42,0,0,False,False
573,5046,2023-12-13 03:57:39,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
574,5046,2023-12-13 04:00:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
575,5046,2023-12-13 04:02:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
576,5046,2023-12-13 04:05:10,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
579,5046,2023-12-13 04:12:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
580,5046,2023-12-13 04:15:11,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
581,5046,2023-12-13 04:17:41,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
582,5046,2023-12-13 04:20:09,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
583,5046,2023-12-13 04:22:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
584,5046,2023-12-13 04:25:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
585,5046,2023-12-13 04:27:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
589,5046,2023-12-13 04:37:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
590,5046,2023-12-13 04:40:11,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
591,5046,2023-12-13 04:42:41,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
592,5046,2023-12-13 04:45:09,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
593,5046,2023-12-13 04:47:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
594,5046,2023-12-13 04:50:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
595,5046,2023-12-13 04:52:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
628,5046,2023-12-13 06:32:39,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
629,5046,2023-12-13 06:36:19,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
630,5046,2023-12-13 06:39:59,0,0,221,20,40,96,43,42,0,0,40,96,43,42,0,0,False,False
631,5046,2023-12-13 06:43:37,0,0,218,18,38,95,42,43,0,0,38,95,42,43,0,0,False,True
632,5046,2023-12-13 06:47:17,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
633,5046,2023-12-13 06:50:58,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
634,5046,2023-12-13 06:54:38,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
638,5046,2023-12-13 07:09:19,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
639,5046,2023-12-13 07:12:59,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
640,5046,2023-12-13 07:16:39,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
641,5046,2023-12-13 07:20:17,0,0,218,18,38,95,42,43,0,0,38,95,42,43,0,0,False,True
642,5046,2023-12-13 07:23:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
643,5046,2023-12-13 07:27:38,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
644,5046,2023-12-13 07:31:18,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
648,5046,2023-12-13 07:45:59,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
649,5046,2023-12-13 07:49:39,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
650,5046,2023-12-13 07:53:19,0,0,221,20,40,96,43,42,0,0,40,96,43,42,0,0,False,False
651,5046,2023-12-13 07:56:57,0,0,218,18,38,95,42,43,0,0,38,95,42,43,0,0,False,True
652,5046,2023-12-13 08:00:38,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
653,5046,2023-12-13 08:04:18,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
654,5046,2023-12-13 08:07:58,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
658,5046,2023-12-13 08:22:39,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
659,5046,2023-12-13 08:26:19,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
660,5046,2023-12-13 08:29:59,0,0,221,20,40,96,43,42,0,0,40,96,43,42,0,0,False,False
661,5046,2023-12-13 08:33:37,0,0,218,18,38,95,42,43,0,0,38,95,42,43,0,0,False,True
662,5046,2023-12-13 08:37:17,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
663,5046,2023-12-13 08:40:58,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
664,5046,2023-12-13 08:44:38,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
668,5046,2023-12-13 08:59:19,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
669,5046,2023-12-13 09:02:59,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
670,5046,2023-12-13 09:06:39,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
671,5046,2023-12-13 09:10:17,0,0,218,18,38,95,42,43,0,0,38,95,42,43,0,0,False,True
672,5046,2023-12-13 09:13:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
673,5046,2023-12-13 09:17:38,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
674,5046,2023-12-13 09:21:18,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
685,5046,2023-12-13 09:56:44,0,0,181,164,30,66,42,43,0,0,30,66,42,43,0,0,False,False
686,5046,2023-12-13 09:59:42,0,0,178,163,28,65,42,43,0,0,28,65,42,43,0,0,False,False
687,5046,2023-12-13 10:02:42,0,0,180,163,30,66,42,42,0,0,30,66,42,42,0,0,False,False
688,5046,2023-12-13 10:07:31,0,0,33,91,30,175,42,42,0,0,30,175,42,42,0,0,False,True
689,5046,2023-12-13 10:11:07,0,0,216,128,36,79,50,51,0,0,36,79,50,51,0,0,False,True
690,5046,2023-12-13 10:14:42,0,0,215,163,36,78,51,50,0,0,36,78,51,50,0,0,False,True
691,5046,2023-12-13 10:17:43,0,0,180,163,30,66,42,42,0,0,30,66,42,42,0,0,False,False
692,5046,2023-12-13 10:20:43,0,0,180,163,30,66,42,42,0,0,30,66,42,42,0,0,False,False
693,5046,2023-12-13 10:23:43,0,0,180,163,30,66,42,42,0,0,30,66,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
912,5046,2023-12-13 22:47:50,0,0,160,150,24,52,42,42,0,0,24,52,42,42,0,0,True,False
913,5046,2023-12-13 22:50:30,0,0,160,150,24,52,42,42,0,0,24,52,42,42,0,0,True,False
914,5046,2023-12-13 22:53:10,0,0,161,150,25,51,43,42,0,0,25,51,43,42,0,0,False,False
915,5046,2023-12-13 22:55:48,0,0,158,148,22,51,42,43,0,0,22,51,42,43,0,0,False,True
916,5046,2023-12-13 22:58:29,0,0,160,149,24,52,42,42,0,0,24,52,42,42,0,0,False,False
917,5046,2023-12-13 23:01:09,0,0,160,149,24,52,42,42,0,0,24,52,42,42,0,0,False,False
918,5046,2023-12-13 23:03:49,0,0,160,149,24,52,42,42,0,0,24,52,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
921,5046,2023-12-13 23:11:50,0,0,160,150,24,52,42,42,0,0,24,52,42,42,0,0,False,False
922,5046,2023-12-13 23:14:30,0,0,160,150,24,52,42,42,0,0,24,52,42,42,0,0,False,False
923,5046,2023-12-13 23:17:10,0,0,161,150,24,52,42,43,0,0,24,52,42,43,0,0,False,False
924,5046,2023-12-13 23:19:48,0,0,158,148,22,51,42,43,0,0,22,51,42,43,0,0,False,True
925,5046,2023-12-13 23:22:28,0,0,160,148,24,52,42,42,0,0,24,52,42,42,0,0,False,False
926,5046,2023-12-13 23:25:08,0,0,160,149,24,52,42,42,0,0,24,52,42,42,0,0,False,False
927,5046,2023-12-13 23:27:49,0,0,160,149,24,52,42,42,0,0,24,52,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
937,5046,2023-12-13 23:52:39,0,0,151,9,24,42,42,43,0,0,24,42,42,43,0,0,False,False
938,5046,2023-12-13 23:55:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
939,5046,2023-12-13 23:57:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
940,5046,2023-12-13 23:59:56,3,1,131,76,26,45,25,35,0,0,26,45,25,35,0,0,False,True
941,5046,2023-12-14 00:00:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
942,5046,2023-12-14 00:02:38,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
943,5046,2023-12-14 00:05:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
944,5046,2023-12-14 00:07:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
945,5046,2023-12-14 00:10:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
949,5046,2023-12-14 00:20:09,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
950,5046,2023-12-14 00:22:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
951,5046,2023-12-14 00:25:10,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
952,5046,2023-12-14 00:27:38,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
953,5046,2023-12-14 00:30:09,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
954,5046,2023-12-14 00:32:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
955,5046,2023-12-14 00:35:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
959,5046,2023-12-14 00:45:09,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
960,5046,2023-12-14 00:47:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
961,5046,2023-12-14 00:50:10,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
962,5046,2023-12-14 00:52:38,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
963,5046,2023-12-14 00:55:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
964,5046,2023-12-14 00:57:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
965,5046,2023-12-14 01:00:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
969,5046,2023-12-14 01:10:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
970,5046,2023-12-14 01:12:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
971,5046,2023-12-14 01:15:10,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
972,5046,2023-12-14 01:17:38,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
973,5046,2023-12-14 01:20:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
974,5046,2023-12-14 01:22:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
975,5046,2023-12-14 01:25:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
979,5046,2023-12-14 01:35:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
980,5046,2023-12-14 01:37:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
981,5046,2023-12-14 01:40:10,0,0,151,10,24,42,43,42,0,0,24,42,43,42,0,0,False,False
982,5046,2023-12-14 01:42:38,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
983,5046,2023-12-14 01:45:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
984,5046,2023-12-14 01:47:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
985,5046,2023-12-14 01:50:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
988,5046,2023-12-14 01:57:39,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
989,5046,2023-12-14 02:00:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
990,5046,2023-12-14 02:02:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
991,5046,2023-12-14 02:05:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
992,5046,2023-12-14 02:07:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
993,5046,2023-12-14 02:10:09,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
994,5046,2023-12-14 02:12:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
998,5046,2023-12-14 02:22:40,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
999,5046,2023-12-14 02:25:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1000,5046,2023-12-14 02:27:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1001,5046,2023-12-14 02:30:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1002,5046,2023-12-14 02:32:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1003,5046,2023-12-14 02:35:09,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1004,5046,2023-12-14 02:37:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1008,5046,2023-12-14 02:47:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1009,5046,2023-12-14 02:50:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1010,5046,2023-12-14 02:52:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1011,5046,2023-12-14 02:55:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1012,5046,2023-12-14 02:57:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1013,5046,2023-12-14 03:00:09,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1014,5046,2023-12-14 03:02:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1018,5046,2023-12-14 03:12:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1019,5046,2023-12-14 03:15:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1020,5046,2023-12-14 03:17:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1021,5046,2023-12-14 03:20:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1022,5046,2023-12-14 03:22:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1023,5046,2023-12-14 03:25:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1024,5046,2023-12-14 03:27:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1028,5046,2023-12-14 03:37:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1029,5046,2023-12-14 03:40:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1030,5046,2023-12-14 03:42:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1031,5046,2023-12-14 03:45:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1032,5046,2023-12-14 03:47:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1033,5046,2023-12-14 03:50:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1034,5046,2023-12-14 03:52:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1038,5046,2023-12-14 04:02:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1039,5046,2023-12-14 04:05:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1040,5046,2023-12-14 04:07:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1041,5046,2023-12-14 04:10:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1042,5046,2023-12-14 04:12:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1043,5046,2023-12-14 04:15:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1044,5046,2023-12-14 04:17:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1048,5046,2023-12-14 04:27:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1049,5046,2023-12-14 04:30:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1050,5046,2023-12-14 04:32:40,0,0,151,10,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1051,5046,2023-12-14 04:35:08,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1052,5046,2023-12-14 04:37:39,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1053,5046,2023-12-14 04:40:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1054,5046,2023-12-14 04:42:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1057,5046,2023-12-14 04:50:10,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1058,5046,2023-12-14 04:52:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1059,5046,2023-12-14 04:55:09,0,0,151,10,24,42,43,42,0,0,24,42,43,42,0,0,False,False
1060,5046,2023-12-14 04:57:38,0,0,148,8,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1061,5046,2023-12-14 05:00:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,True,False
1062,5046,2023-12-14 05:03:40,0,0,212,140,42,59,55,56,0,0,42,59,55,56,0,0,True,True
1063,5046,2023-12-14 05:06:20,0,0,160,141,32,44,42,42,0,0,32,44,42,42,0,0,True,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1091,5046,2023-12-14 06:32:38,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1092,5046,2023-12-14 06:36:18,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1093,5046,2023-12-14 06:39:58,0,0,221,19,40,96,42,43,0,0,40,96,42,43,0,0,False,False
1094,5046,2023-12-14 06:43:37,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1095,5046,2023-12-14 06:47:17,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1096,5046,2023-12-14 06:50:57,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1097,5046,2023-12-14 06:54:37,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1101,5046,2023-12-14 07:09:18,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1102,5046,2023-12-14 07:12:58,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1103,5046,2023-12-14 07:16:39,0,0,221,19,40,96,42,43,0,0,40,96,42,43,0,0,False,False
1104,5046,2023-12-14 07:20:17,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1105,5046,2023-12-14 07:23:57,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1106,5046,2023-12-14 07:27:37,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1107,5046,2023-12-14 07:31:18,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1111,5046,2023-12-14 07:45:58,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1112,5046,2023-12-14 07:49:38,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1113,5046,2023-12-14 07:53:18,0,0,221,19,40,96,42,43,0,0,40,96,42,43,0,0,False,False
1114,5046,2023-12-14 07:56:57,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1115,5046,2023-12-14 08:00:37,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1116,5046,2023-12-14 08:04:17,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1117,5046,2023-12-14 08:07:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1121,5046,2023-12-14 08:22:38,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1122,5046,2023-12-14 08:26:19,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1123,5046,2023-12-14 08:29:59,0,0,221,19,40,96,42,43,0,0,40,96,42,43,0,0,False,False
1124,5046,2023-12-14 08:33:37,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1125,5046,2023-12-14 08:37:17,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1126,5046,2023-12-14 08:40:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1127,5046,2023-12-14 08:44:37,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1131,5046,2023-12-14 08:59:18,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1132,5046,2023-12-14 09:02:59,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1133,5046,2023-12-14 09:06:39,0,0,221,19,40,96,42,43,0,0,40,96,42,43,0,0,False,False
1134,5046,2023-12-14 09:10:17,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1135,5046,2023-12-14 09:13:57,0,0,220,17,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1136,5046,2023-12-14 09:17:37,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1137,5046,2023-12-14 09:21:17,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1405,5046,2023-12-14 22:53:09,0,0,158,149,22,51,42,43,0,0,22,51,42,43,0,0,False,True
1406,5046,2023-12-14 22:55:49,0,0,160,150,24,52,42,42,0,0,24,52,42,42,0,0,False,False
1407,5046,2023-12-14 22:58:39,0,0,169,159,24,61,42,42,0,0,24,61,42,42,0,0,False,False
1408,5046,2023-12-14 23:01:11,0,0,152,151,19,49,42,42,0,0,19,49,42,42,0,0,False,True
1409,5046,2023-12-14 23:03:51,0,0,161,151,24,52,42,43,0,0,24,52,42,43,0,0,False,False
1410,5046,2023-12-14 23:06:29,0,0,158,149,22,51,42,43,0,0,22,51,42,43,0,0,False,True
1411,5046,2023-12-14 23:09:09,0,0,160,149,24,52,42,42,0,0,24,52,42,42,0,0,False,False
1412,5046,2023-12-14 23:11:49,0,0,160,149,24,52,42,42,0,0,24,52,42,42,0,0,False,False
1413,5046,2023-12-14 23:14:29,0,0,160,150,24,52,42,42,0,0,24,52,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1428,5046,2023-12-14 23:52:40,0,0,150,10,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1429,5046,2023-12-14 23:55:11,0,0,150,11,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1430,5046,2023-12-14 23:57:41,0,0,151,11,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1431,5046,2023-12-14 23:59:46,3,1,131,67,33,34,30,34,0,0,33,34,30,34,0,0,False,True
1432,5046,2023-12-15 00:00:09,0,0,148,9,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1433,5046,2023-12-15 00:02:37,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1434,5046,2023-12-15 00:05:08,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1435,5046,2023-12-15 00:07:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1436,5046,2023-12-15 00:10:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1440,5046,2023-12-15 00:20:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1441,5046,2023-12-15 00:22:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1442,5046,2023-12-15 00:25:09,0,0,151,9,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1443,5046,2023-12-15 00:27:37,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1444,5046,2023-12-15 00:30:07,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1445,5046,2023-12-15 00:32:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1446,5046,2023-12-15 00:35:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1450,5046,2023-12-15 00:45:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1451,5046,2023-12-15 00:47:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1452,5046,2023-12-15 00:50:09,0,0,151,9,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1453,5046,2023-12-15 00:52:37,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1454,5046,2023-12-15 00:55:08,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1455,5046,2023-12-15 00:57:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1456,5046,2023-12-15 01:00:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1460,5046,2023-12-15 01:10:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1461,5046,2023-12-15 01:12:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1462,5046,2023-12-15 01:15:09,0,0,151,9,24,42,43,42,0,0,24,42,43,42,0,0,False,False
1463,5046,2023-12-15 01:17:37,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1464,5046,2023-12-15 01:20:08,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1465,5046,2023-12-15 01:22:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1466,5046,2023-12-15 01:25:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1470,5046,2023-12-15 01:35:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1471,5046,2023-12-15 01:37:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1472,5046,2023-12-15 01:40:09,0,0,151,9,24,42,43,42,0,0,24,42,43,42,0,0,False,False
1473,5046,2023-12-15 01:42:38,0,0,148,8,22,42,41,43,0,0,22,42,41,43,0,0,False,True
1474,5046,2023-12-15 01:45:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1475,5046,2023-12-15 01:47:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1476,5046,2023-12-15 01:50:08,0,0,151,8,25,42,42,42,0,0,25,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1478,5046,2023-12-15 01:55:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1479,5046,2023-12-15 01:57:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1480,5046,2023-12-15 02:00:09,0,0,151,9,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1481,5046,2023-12-15 02:02:37,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1482,5046,2023-12-15 02:05:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1483,5046,2023-12-15 02:07:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1484,5046,2023-12-15 02:10:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1488,5046,2023-12-15 02:20:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1489,5046,2023-12-15 02:22:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1490,5046,2023-12-15 02:25:10,0,0,151,9,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1491,5046,2023-12-15 02:27:38,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1492,5046,2023-12-15 02:30:08,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1493,5046,2023-12-15 02:32:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1494,5046,2023-12-15 02:35:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1498,5046,2023-12-15 02:45:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1499,5046,2023-12-15 02:47:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1500,5046,2023-12-15 02:50:10,0,0,151,9,24,42,43,42,0,0,24,42,43,42,0,0,False,False
1501,5046,2023-12-15 02:52:38,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1502,5046,2023-12-15 02:55:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1503,5046,2023-12-15 02:57:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1504,5046,2023-12-15 03:00:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1508,5046,2023-12-15 03:10:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1509,5046,2023-12-15 03:12:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1510,5046,2023-12-15 03:15:10,0,0,151,9,24,42,43,42,0,0,24,42,43,42,0,0,False,False
1511,5046,2023-12-15 03:17:38,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1512,5046,2023-12-15 03:20:08,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1513,5046,2023-12-15 03:22:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1514,5046,2023-12-15 03:25:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1518,5046,2023-12-15 03:35:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1519,5046,2023-12-15 03:37:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1520,5046,2023-12-15 03:40:10,0,0,151,9,24,42,43,42,0,0,24,42,43,42,0,0,False,False
1521,5046,2023-12-15 03:42:38,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1522,5046,2023-12-15 03:45:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1523,5046,2023-12-15 03:47:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1524,5046,2023-12-15 03:50:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1527,5046,2023-12-15 03:57:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1528,5046,2023-12-15 04:00:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1529,5046,2023-12-15 04:02:40,0,0,151,9,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1530,5046,2023-12-15 04:05:07,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1531,5046,2023-12-15 04:07:38,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1532,5046,2023-12-15 04:10:08,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1533,5046,2023-12-15 04:12:38,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1537,5046,2023-12-15 04:22:39,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1538,5046,2023-12-15 04:25:09,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1539,5046,2023-12-15 04:27:38,0,0,151,9,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1540,5046,2023-12-15 04:30:07,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1541,5046,2023-12-15 04:32:37,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1542,5046,2023-12-15 04:35:07,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1543,5046,2023-12-15 04:37:37,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1547,5046,2023-12-15 04:47:38,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1548,5046,2023-12-15 04:50:08,0,0,150,9,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1549,5046,2023-12-15 04:52:39,0,0,151,9,24,42,42,43,0,0,24,42,42,43,0,0,False,False
1550,5046,2023-12-15 04:55:07,0,0,148,7,22,41,42,43,0,0,22,41,42,43,0,0,False,True
1551,5046,2023-12-15 04:57:37,0,0,150,7,24,42,42,42,0,0,24,42,42,42,0,0,False,False
1552,5046,2023-12-15 05:00:07,0,0,150,8,24,42,42,42,0,0,24,42,42,42,0,0,True,False
1553,5046,2023-12-15 05:03:39,0,0,212,140,42,59,55,56,0,0,42,59,55,56,0,0,True,True

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1582,5046,2023-12-15 06:32:38,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1583,5046,2023-12-15 06:36:18,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1584,5046,2023-12-15 06:39:59,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
1585,5046,2023-12-15 06:43:37,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1586,5046,2023-12-15 06:47:17,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1587,5046,2023-12-15 06:50:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1588,5046,2023-12-15 06:54:37,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1592,5046,2023-12-15 07:09:19,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1593,5046,2023-12-15 07:12:59,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1594,5046,2023-12-15 07:16:39,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
1595,5046,2023-12-15 07:20:17,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1596,5046,2023-12-15 07:23:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1597,5046,2023-12-15 07:27:38,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1598,5046,2023-12-15 07:31:18,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1602,5046,2023-12-15 07:45:58,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1603,5046,2023-12-15 07:49:39,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1604,5046,2023-12-15 07:53:19,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
1605,5046,2023-12-15 07:56:57,0,0,218,18,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1606,5046,2023-12-15 08:00:37,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1607,5046,2023-12-15 08:04:18,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1608,5046,2023-12-15 08:07:58,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1612,5046,2023-12-15 08:22:39,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1613,5046,2023-12-15 08:26:19,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1614,5046,2023-12-15 08:29:59,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
1615,5046,2023-12-15 08:33:37,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1616,5046,2023-12-15 08:37:17,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1617,5046,2023-12-15 08:40:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1618,5046,2023-12-15 08:44:38,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1622,5046,2023-12-15 08:59:19,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1623,5046,2023-12-15 09:02:59,0,0,220,19,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1624,5046,2023-12-15 09:06:39,0,0,221,19,40,96,43,42,0,0,40,96,43,42,0,0,False,False
1625,5046,2023-12-15 09:10:17,0,0,218,17,38,95,42,43,0,0,38,95,42,43,0,0,False,True
1626,5046,2023-12-15 09:13:57,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1627,5046,2023-12-15 09:17:37,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False
1628,5046,2023-12-15 09:21:18,0,0,220,18,40,96,42,42,0,0,40,96,42,42,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1778,5046,2023-12-15 16:53:44,0,0,180,164,30,66,42,42,0,0,30,66,42,42,0,0,False,False
1779,5046,2023-12-15 16:56:44,0,0,181,165,30,66,42,43,0,0,30,66,42,43,0,0,False,False
1780,5046,2023-12-15 16:59:42,0,0,178,163,28,65,42,43,0,0,28,65,42,43,0,0,False,False
1781,5046,2023-12-15 23:59:30,3,1,130,51,36,14,27,27,26,0,36,14,27,27,26,0,False,True

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
229,5047,2023-12-12 11:44:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
230,5047,2023-12-12 11:47:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
231,5047,2023-12-12 11:51:42,3,1,146,42,0,75,26,45,0,0,0,75,26,45,0,0,False,False
232,5047,2023-12-12 11:53:50,0,0,128,170,25,39,20,44,0,0,25,39,20,44,0,0,False,True
233,5047,2023-12-12 11:56:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
234,5047,2023-12-12 11:59:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
235,5047,2023-12-12 12:02:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
681,5047,2023-12-13 09:56:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
682,5047,2023-12-13 09:59:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
683,5047,2023-12-13 10:02:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
684,5047,2023-12-13 10:07:36,3,1,30,96,35,181,26,44,0,0,35,181,26,44,0,0,False,True
685,5047,2023-12-13 10:09:42,0,0,126,42,25,37,20,44,0,0,25,37,20,44,0,0,False,True
686,5047,2023-12-13 10:12:13,3,2,151,13,28,59,20,44,0,0,28,59,20,44,0,0,False,True
687,5047,2023-12-13 10:14:50,3,2,157,170,30,63,20,44,0,0,30,63,20,44,0,0,False,True
688,5047,2023-12-13 10:17:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
689,5047,2023-12-13 10:20:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
690,5047,2023-12-13 10:23:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
722,5047,2023-12-13 11:59:49,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
723,5047,2023-12-13 12:02:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
724,5047,2023-12-13 12:05:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
725,5047,2023-12-13 12:11:13,3,1,50,133,0,0,0,50,0,0,0,0,0,50,0,0,False,True
726,5047,2023-12-13 12:13:19,0,0,126,79,25,37,20,44,0,0,25,37,20,44,0,0,False,True
727,5047,2023-12-13 12:17:18,3,2,239,138,46,100,35,58,0,0,46,100,35,58,0,0,False,True
728,5047,2023-12-13 12:20:50,3,2,212,170,41,89,30,52,0,0,41,89,30,52,0,0,False,True
729,5047,2023-12-13 12:23:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
730,5047,2023-12-13 12:26:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
731,5047,2023-12-13 12:29:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
907,5047,2023-12-13 22:47:54,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,True,False
908,5047,2023-12-13 22:50:34,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,True,False
909,5047,2023-12-13 22:53:14,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
910,5047,2023-12-13 22:56:53,3,1,220,53,31,125,20,44,0,0,31,125,20,44,0,0,False,True
911,5047,2023-12-13 22:58:59,0,0,126,19,25,37,20,44,0,0,25,37,20,44,0,0,False,True
912,5047,2023-12-13 23:01:14,3,2,135,154,25,46,20,44,0,0,25,46,20,44,0,0,False,True
913,5047,2023-12-13 23:03:54,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
914,5047,2023-12-13 23:06:34,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
915,5047,2023-12-13 23:09:14,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1190,5047,2023-12-14 12:23:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1191,5047,2023-12-14 12:26:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1192,5047,2023-12-14 12:30:00,3,1,145,0,0,75,26,44,0,0,0,75,26,44,0,0,False,False
1193,5047,2023-12-14 12:32:50,0,0,170,170,33,71,22,44,0,0,33,71,22,44,0,0,False,True
1194,5047,2023-12-14 12:35:50,3,1,180,169,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1195,5047,2023-12-14 12:38:51,3,1,181,170,35,76,26,44,0,0,35,76,26,44,0,0,False,False
1196,5047,2023-12-14 12:41:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1261,5047,2023-12-14 15:56:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1262,5047,2023-12-14 15:59:51,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1263,5047,2023-12-14 16:02:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1264,5047,2023-12-14 16:08:46,3,1,99,165,35,75,26,219,0,0,35,75,26,219,0,0,False,True
1265,5047,2023-12-14 16:10:52,0,0,126,111,25,37,20,44,0,0,25,37,20,44,0,0,False,True
1266,5047,2023-12-14 16:14:51,3,2,239,170,46,100,35,58,0,0,46,100,35,58,0,0,False,True
1267,5047,2023-12-14 16:17:51,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1268,5047,2023-12-14 16:20:51,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1269,5047,2023-12-14 16:23:51,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1396,5047,2023-12-14 22:53:14,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
1397,5047,2023-12-14 22:55:54,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
1398,5047,2023-12-14 22:58:59,0,0,185,19,56,65,20,44,0,0,56,65,20,44,0,0,False,False
1399,5047,2023-12-14 23:01:14,0,0,135,154,25,46,20,44,0,0,25,46,20,44,0,0,False,True
1400,5047,2023-12-14 23:03:54,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
1401,5047,2023-12-14 23:06:35,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False
1402,5047,2023-12-14 23:09:14,3,1,160,154,31,65,20,44,0,0,31,65,20,44,0,0,False,False

,현장교차로ID,수집날짜시각,제어구분코드,제어상태코드,주기시간,옵셋시간,A링1현시시간,A링2현시시간,A링3현시시간,A링4현시시간,A링5현시시간,A링6현시시간,B링1현시시간,B링2현시시간,B링3현시시간,B링4현시시간,B링5현시시간,B링6현시시간,전이시간여부,이상치존재
1684,5047,2023-12-15 12:41:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1685,5047,2023-12-15 12:44:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1686,5047,2023-12-15 12:49:13,3,1,70,72,0,0,26,44,0,0,0,0,26,44,0,0,False,False
1687,5047,2023-12-15 12:51:19,0,0,126,18,25,37,20,44,0,0,25,37,20,44,0,0,False,True
1688,5047,2023-12-15 12:53:51,3,2,152,170,28,60,20,44,0,0,28,60,20,44,0,0,False,True
1689,5047,2023-12-15 12:56:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1690,5047,2023-12-15 12:59:51,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False
1691,5047,2023-12-15 13:02:50,3,1,180,170,35,75,26,44,0,0,35,75,26,44,0,0,False,False

In [11]:
# context = []
# for i in (hstr.제어상태코드==2).index:
#     start_idx = max(idx - k, 0)  # 데이터프레임의 시작을 넘어가지 않도록 합니다.
#     end_idx = min(idx + k + 1, len(hstr))  # 데이터프레임의 끝을 넘어가지 않도록 합니다.
#     context_indices.extend(range(start_idx, end_idx))
#     context.extend(list(range(i-k,i+k)))
# hstr[hstr.index.isin(context)]